export type SettingInputType = "string" | "number" | "boolean" | "enum";

export interface SettingUIMetadata {
  key: string;
  titleEn: string;
  titleAr: string;
  inputType: SettingInputType;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  defaultValue: any;
  descEn: string;
  descAr: string;
  options?: { value: string; label: string; labelAr?: string }[]; // For enums
  min?: number;
  max?: number;
  placeholder?: string;
}

export const SETTINGS_UI_REGISTRY: Record<string, SettingUIMetadata> = {
  // Billing
  "billing.default_currency": {
    key: "billing.default_currency",
    titleEn: "Default Currency",
    titleAr: "العملة الافتراضية",
    inputType: "enum",
    defaultValue: "USD",
    descEn: "Default ISO-4217 currency code used when issuing invoices.",
    descAr: "كود العملة الافتراضي بصيغة ISO-4217 المستخدم عند إصدار الفواتير.",
    options: [
      { value: "USD", label: "US Dollar (USD)", labelAr: "دولار أمريكي (USD)" },
      { value: "EUR", label: "Euro (EUR)", labelAr: "يورو (EUR)" },
      { value: "EGP", label: "Egyptian Pound (EGP)", labelAr: "جنيه مصري (EGP)" },
      { value: "AED", label: "UAE Dirham (AED)", labelAr: "درهم إماراتي (AED)" },
      { value: "SAR", label: "Saudi Riyal (SAR)", labelAr: "ريال سعودي (SAR)" },
    ],
  },

  "billing.invoice_due_days": {
    key: "billing.invoice_due_days",
    titleEn: "Invoice Payment Due Days",
    titleAr: "عدد أيام استحقاق الفاتورة",
    inputType: "number",
    defaultValue: 14,
    descEn: "Number of days given to pay an issued invoice before it becomes overdue.",
    descAr: "عدد الأيام المتاحة لدفع الفاتورة الصادرة قبل اعتبارها متأخرة.",
    min: 1,
    max: 365,
  },
  "billing.dunning_grace_days": {
    key: "billing.dunning_grace_days",
    titleEn: "Dunning Grace Period (Days)",
    titleAr: "فترة السماح للمتأخرات (أيام)",
    inputType: "number",
    defaultValue: 7,
    descEn: "Number of days an overdue subscription remains in owner-accessible dunning before escalation.",
    descAr: "عدد الأيام التي يظل فيها الاشتراك المتأخر متاحا للمالك للسداد قبل التصعيد.",
    min: 0,
    max: 90,
  },
  "billing.min_topup_usd": {
    key: "billing.min_topup_usd",
    titleEn: "Minimum Wallet Top-up (USD)",
    titleAr: "الحد الأدنى لشحن المحفظة ($)",
    inputType: "number",
    defaultValue: 1,
    descEn: "Minimum canonical USD value allowed for a wallet top-up.",
    descAr: "الحد الأدنى للقيمة الدولارية الفعلية لشحن المحفظة.",
    min: 1,
    max: 1000000000,
  },
  "billing.max_topup_usd": {
    key: "billing.max_topup_usd",
    titleEn: "Maximum Wallet Top-up (USD)",
    titleAr: "الحد الأقصى لشحن المحفظة ($)",
    inputType: "number",
    defaultValue: 100000,
    descEn: "Maximum canonical USD value allowed for a wallet top-up.",
    descAr: "الحد الأقصى للقيمة الدولارية الفعلية لشحن المحفظة.",
    min: 1,
    max: 1000000000,
  },

  // Tenants
  "tenants.trial_days": {
    key: "tenants.trial_days",
    titleEn: "Default Trial Period (Days)",
    titleAr: "مدة التجربة الافتراضية (أيام)",
    inputType: "number",
    defaultValue: 14,
    descEn: "Length in days of the default trial subscription period.",
    descAr: "مدة فترة التجربة الافتراضية للاشتراك بالأيام.",
    min: 1,
    max: 365,
  },

  // Auth
  "auth.invite_token_ttl_minutes": {
    key: "auth.invite_token_ttl_minutes",
    titleEn: "Invite Token TTL (Minutes)",
    titleAr: "صلاحية رابط الدعوة (دقائق)",
    inputType: "number",
    defaultValue: 1440,
    descEn: "Time-to-live, in minutes, of invitation tokens.",
    descAr: "مدة صلاحية رموز الدعوة بالدقائق.",
    min: 5,
    max: 43200,
  },
  "auth.reset_token_ttl_minutes": {
    key: "auth.reset_token_ttl_minutes",
    titleEn: "Password Reset Token TTL (Minutes)",
    titleAr: "صلاحية رابط إعادة كلمة المرور (دقائق)",
    inputType: "number",
    defaultValue: 60,
    descEn: "Time-to-live, in minutes, of password-reset tokens.",
    descAr: "مدة صلاحية رموز إعادة تعيين كلمة المرور بالدقائق.",
    min: 5,
    max: 1440,
  },

  // Platform & Support
  "support.email": {
    key: "support.email",
    titleEn: "Platform Support Email",
    titleAr: "البريد الإلكتروني للدعم الفني",
    inputType: "string",
    defaultValue: "support@mutakamel.ai",
    descEn: "Support contact address shown across the admin portal.",
    descAr: "عنوان بريد الدعم الظاهر في بوابة الإدارة.",
    placeholder: "support@mutakamel.ai",
  },
  "platform.maintenance_mode": {
    key: "platform.maintenance_mode",
    titleEn: "System Maintenance Mode",
    titleAr: "وضع الصيانة العام للمنصة",
    inputType: "boolean",
    defaultValue: false,
    descEn: "When true, tenant logins are blocked for maintenance.",
    descAr: "عند تفعيله، يتم منع تسجيل دخول المستأجرين لأغراض الصيانة.",
  },

  // Asterisk WebRTC
  "asterisk.enabled": {
    key: "asterisk.enabled",
    titleEn: "Enable Asterisk WebRTC Phone",
    titleAr: "تفعيل هاتف Asterisk WebRTC",
    inputType: "boolean",
    defaultValue: false,
    descEn: "Enables the Admin Portal WebRTC phone Asterisk integration.",
    descAr: "تفعيل تكامل هاتف WebRTC مع Asterisk في لوحة الإدارة.",
  },
  "asterisk.websocket_url": {
    key: "asterisk.websocket_url",
    titleEn: "Asterisk WebSocket URL",
    titleAr: "رابط WebSocket لـ Asterisk",
    inputType: "string",
    defaultValue: "wss://callcenter.mersany.com:8089/ws",
    descEn: "Asterisk WebSocket URL used by JsSIP, usually ws:// or wss://.",
    descAr: "رابط WebSocket الخاص بـ Asterisk المستخدم بواسطة JsSIP.",
    placeholder: "wss://callcenter.mersany.com:8089/ws",
  },
  "asterisk.websocket_url_secondary": {
    key: "asterisk.websocket_url_secondary",
    titleEn: "Secondary Asterisk WebSocket URL (Failover)",
    titleAr: "رابط WebSocket احتياطي لـ Asterisk (تحويل عند الانقطاع)",
    inputType: "string",
    defaultValue: "",
    descEn: "Optional backup WebSocket URL. JsSIP connects to the primary URL first and only switches to this one if it disconnects.",
    descAr: "رابط WebSocket احتياطي اختياري. يتصل JsSIP بالرابط الأساسي أولاً وينتقل لهذا الرابط فقط عند انقطاع الاتصال.",
    placeholder: "wss://backup.callcenter.mersany.com:8089/ws",
  },
  "asterisk.sip_domain": {
    key: "asterisk.sip_domain",
    titleEn: "SIP Domain",
    titleAr: "نطاق SIP (Domain)",
    inputType: "string",
    defaultValue: "callcenter.mersany.com",
    descEn: "SIP domain used to build SIP URIs for the WebRTC phone.",
    descAr: "دومين SIP المستخدم لتكوين عناوين SIP الخاص بهاتف WebRTC.",
    placeholder: "callcenter.mersany.com",
  },
  "asterisk.realm": {
    key: "asterisk.realm",
    titleEn: "SIP Authentication Realm",
    titleAr: "نطاق المصادقة (Realm)",
    inputType: "string",
    defaultValue: "asterisk",
    descEn: "Optional SIP authentication realm.",
    descAr: "نطاق مصادقة SIP الاختياري.",
    placeholder: "asterisk",
  },
  "asterisk.outbound_proxy": {
    key: "asterisk.outbound_proxy",
    titleEn: "Outbound SIP Proxy",
    titleAr: "خادم البروكسي الخارجي (Outbound Proxy)",
    inputType: "string",
    defaultValue: "",
    descEn: "Optional outbound SIP proxy route, for example sip:proxy.example.com.",
    descAr: "مسار outbound proxy اختياري لـ SIP.",
    placeholder: "sip:proxy.example.com",
  },
  "asterisk.default_caller_id": {
    key: "asterisk.default_caller_id",
    titleEn: "Default Caller ID",
    titleAr: "رقم المتصل الافتراضي (Caller ID)",
    inputType: "string",
    defaultValue: "",
    descEn: "Default caller ID used when a user does not override it.",
    descAr: "رقم caller ID الافتراضي عند عدم ضبطه.",
    placeholder: "+1234567890",
  },
  "asterisk.from_domain": {
    key: "asterisk.from_domain",
    titleEn: "From Domain Override",
    titleAr: "تجاوز نطاق From Domain",
    inputType: "string",
    defaultValue: "",
    descEn: "Optional From domain override.",
    descAr: "دومين From اختياري عند الحاجة.",
  },
  "asterisk.registrar_server": {
    key: "asterisk.registrar_server",
    titleEn: "Registrar Server URI",
    titleAr: "عنوان خادم التسجيل (Registrar URI)",
    inputType: "string",
    defaultValue: "",
    descEn: "Optional SIP registrar server URI.",
    descAr: "عنوان SIP registrar server اختياري.",
  },
  "asterisk.contact_uri": {
    key: "asterisk.contact_uri",
    titleEn: "Contact URI Override",
    titleAr: "تجاوز عنوان Contact URI",
    inputType: "string",
    defaultValue: "",
    descEn: "Optional SIP contact URI override.",
    descAr: "عنوان SIP contact URI اختياري.",
  },
  "asterisk.register_expires": {
    key: "asterisk.register_expires",
    titleEn: "SIP Registration Expiry (Seconds)",
    titleAr: "مدة صلاحية التسجيل (ثواني)",
    inputType: "number",
    defaultValue: 600,
    descEn: "SIP registration expiry in seconds.",
    descAr: "مدة انتهاء تسجيل SIP بالثواني.",
    min: 30,
    max: 86400,
  },
  "asterisk.session_timers": {
    key: "asterisk.session_timers",
    titleEn: "Enable Session Timers",
    titleAr: "تفعيل مؤقتات الجلسة (Session Timers)",
    inputType: "boolean",
    defaultValue: false,
    descEn: "Enables SIP session timers in JsSIP.",
    descAr: "تفعيل SIP session timers في JsSIP.",
  },
  "asterisk.trace_sip": {
    key: "asterisk.trace_sip",
    titleEn: "Enable Verbose SIP Tracing",
    titleAr: "تفعيل تتبع بروتوكول SIP المفصل",
    inputType: "boolean",
    defaultValue: false,
    descEn: "Enables verbose SIP tracing in the browser console.",
    descAr: "تفعيل تتبع SIP التفصيلي في console المتصفح.",
  },
  "asterisk.allow_invalid_tls_certificate": {
    key: "asterisk.allow_invalid_tls_certificate",
    titleEn: "Allow Invalid Backend TLS Certificates",
    titleAr: "السماح شهادات TLS غير موثوقة في الخادم الخفي",
    inputType: "boolean",
    defaultValue: false,
    descEn: "Documents whether invalid Asterisk TLS certificates are accepted by a backend proxy.",
    descAr: "يوضح هل يتم قبول شهادات TLS غير الموثوقة عبر proxy خلفي.",
  },
  "asterisk.stun_servers": {
    key: "asterisk.stun_servers",
    titleEn: "STUN Servers",
    titleAr: "سيرفرات STUN",
    inputType: "string",
    defaultValue: "stun:stun.l.google.com:19302",
    descEn: "Comma-separated STUN server URLs.",
    descAr: "قائمة STUN server URLs مفصولة بفواصل.",
  },
  "asterisk.turn_servers_json": {
    key: "asterisk.turn_servers_json",
    titleEn: "TURN Servers (JSON Array)",
    titleAr: "سيرفرات TURN (مصفوفة JSON)",
    inputType: "string",
    defaultValue: "[]",
    descEn: "TURN server JSON array compatible with RTCIceServer.",
    descAr: "مصفوفة JSON لسيرفرات TURN متوافقة مع RTCIceServer.",
  },
  "asterisk.turn_rest_enabled": {
    key: "asterisk.turn_rest_enabled",
    titleEn: "Mint Short-Lived TURN Credentials",
    titleAr: "إصدار بيانات اعتماد TURN قصيرة الأجل",
    inputType: "boolean",
    defaultValue: false,
    descEn: "Requires TURN REST URIs below and the ASTERISK_TURN_SHARED_SECRET server environment variable. Otherwise has no effect.",
    descAr: "يتطلب ضبط عناوين TURN REST أدناه ومتغير البيئة ASTERISK_TURN_SHARED_SECRET على الخادم، وإلا فلا تأثير له.",
  },
  "asterisk.turn_rest_ttl_seconds": {
    key: "asterisk.turn_rest_ttl_seconds",
    titleEn: "TURN Credential Lifetime (Seconds)",
    titleAr: "مدة صلاحية بيانات اعتماد TURN (ثواني)",
    inputType: "number",
    defaultValue: 3600,
    descEn: "How long each minted TURN credential remains valid.",
    descAr: "المدة التي تبقى فيها بيانات اعتماد TURN المُصدرة صالحة.",
    min: 60,
    max: 86400,
  },
  "asterisk.turn_rest_uris": {
    key: "asterisk.turn_rest_uris",
    titleEn: "TURN REST Server URIs",
    titleAr: "عناوين خوادم TURN REST",
    inputType: "string",
    defaultValue: "",
    descEn: "Comma-separated TURN server URIs the minted credential is valid for.",
    descAr: "عناوين خوادم TURN مفصولة بفواصل تصلح لها بيانات الاعتماد المُصدرة.",
    placeholder: "turn:turn.example.com:3478?transport=udp",
  },
  "asterisk.ice_servers_json": {
    key: "asterisk.ice_servers_json",
    titleEn: "Additional ICE Servers (JSON Array)",
    titleAr: "سيرفرات ICE الإضافية (مصفوفة JSON)",
    inputType: "string",
    defaultValue: "[]",
    descEn: "Additional ICE server JSON array compatible with RTCIceServer.",
    descAr: "مصفوفة JSON إضافية لسيرفرات ICE متوافقة مع RTCIceServer.",
  },
  "asterisk.ice_transport_policy": {
    key: "asterisk.ice_transport_policy",
    titleEn: "ICE Transport Policy",
    titleAr: "سياسة نقل ICE",
    inputType: "enum",
    defaultValue: "all",
    descEn: "'Relay only' forces all call media through a TURN server instead of attempting a direct/STUN path. Use behind restrictive NATs or firewalls.",
    descAr: "يفرض خيار \"عبر TURN فقط\" توجيه كل وسائط المكالمة عبر خادم TURN بدلاً من محاولة اتصال مباشر/STUN. يُستخدم خلف جدران الحماية أو NAT المقيدة.",
    options: [
      { value: "all", label: "All (direct + relay)", labelAr: "الكل (مباشر + عبر TURN)" },
      { value: "relay", label: "Relay only (force TURN)", labelAr: "عبر TURN فقط (إجباري)" },
    ],
  },
  "asterisk.extra_json": {
    key: "asterisk.extra_json",
    titleEn: "Extra Provider Options (JSON)",
    titleAr: "خيارات المزود الإضافية (كائن JSON)",
    inputType: "string",
    defaultValue: "{}",
    descEn: "Reserved JSON object for provider-specific Asterisk WebRTC options.",
    descAr: "كائن JSON اختياري لإعدادات Asterisk WebRTC الخاصة بالمزود.",
  },

  // Notifications
  "notifications.in_app_enabled": {
    key: "notifications.in_app_enabled",
    titleEn: "In-App Notifications",
    titleAr: "الإشعارات الداخلية في النظام",
    inputType: "boolean",
    defaultValue: true,
    descEn: "Enables persisted in-app notifications across portals.",
    descAr: "تفعيل الإشعارات الداخلية المحفوظة عبر البوابات.",
  },
  "notifications.realtime_enabled": {
    key: "notifications.realtime_enabled",
    titleEn: "Realtime WebSocket Notifications",
    titleAr: "الإشعارات اللحظية (WebSockets)",
    inputType: "boolean",
    defaultValue: false,
    descEn: "Enables realtime notification fan-out to connected clients.",
    descAr: "تفعيل بث الإشعارات اللحظية للعملاء المتصلين.",
  },
  "notifications.push_enabled": {
    key: "notifications.push_enabled",
    titleEn: "Web & Mobile Push Notifications",
    titleAr: "إشعارات الدفع (Push Notifications)",
    inputType: "boolean",
    defaultValue: false,
    descEn: "Enables web and mobile push notification delivery.",
    descAr: "تفعيل إرسال إشعارات الدفع للويب والموبايل.",
  },
  "notifications.email_enabled": {
    key: "notifications.email_enabled",
    titleEn: "Email Notifications Channel",
    titleAr: "قناة إشعارات البريد الإلكتروني",
    inputType: "boolean",
    defaultValue: false,
    descEn: "Enables email delivery for notification events that request it.",
    descAr: "تفعيل إرسال البريد للإشعارات التي تطلب قناة البريد.",
  },
};
