const en = {
  creation: "Initial tenant commercial quote", seed: "First subscription for an existing tenant",
  boundary: "This quote prices the selected applications and addons. It does not create a tenant, prove installation readiness or assign users.",
  selectedOnly: "Review selected application and addon quantities. Removing an application also removes its selected addons.",
  options: "Initial application and addon catalogue", loadOptions: "Load current catalogue options", loadingOptions: "Loading catalogue options…",
  optionsBoundary: "These published choices contain no prices or installation assurance. A fresh server quote must validate the complete selection.",
  optionsForbidden: "Loading these options requires tenant-create permission. Supplied selections can still be reviewed with quote permission.",
  optionsEmpty: "No applications were returned by the current catalogue.", chooseTier: "Choose a tier", addApplication: "Add application", addAddon: "Add addon",
  selected: "Selected", blocked: "Catalogue diagnostics", incompatible: "Choose a compatible parent tier before adding this addon.",
  changeTier: "To change a selected tier, remove the application and its addons, then add it with the required tier.",
  cycle: "Billing cycle", monthly: "Monthly", annual: "Annual", trial: "Trial days", trialDefault: "Leave blank for the server's configured trial duration.",
  application: "Application", tier: "Tier", addon: "Addon", definition: "Selected definition", baseSeats: "Base application seats", addonSeats: "Addon seats",
  invalidSeats: "Use a whole number from 1 to 100000. Addon seats cannot exceed the parent application seats.",
  invalid: "Review the selected applications, quantities and trial duration.", invalidTrial: "Use 1–365 whole days, or leave blank.",
  removeApplication: "Remove application and its addons", removeAddon: "Remove addon", restore: "Restore supplied selections",
  quote: "Request server quote", quoting: "Requesting a quote…", noQuote: "Request a quote to see authoritative graduated per-user prices.",
  expired: "This quote has expired. Request a new quote before starting a new command.",
  base: "Base recurring USD", addons: "Addon recurring USD", combined: "Combined recurring USD", seats: "Quoted seats",
  allowance: "Addon quantities do not increase the base application's user allowance.", resolvedTrial: "Server-resolved trial days", expires: "Quote expires at", quoteId: "Quote ID",
  brackets: "Server-priced marginal brackets", from: "From", through: "Through", open: "No upper limit", charged: "Charged users", unit: "USD / user", amount: "Amount USD",
  forbidden: "The current permissions do not allow requesting an initial quote.", seedForbidden: "Creating the first subscription requires subscription-create and critical permissions together.",
  initialExists: "An existing subscription was observed. This is not an existing-subscription change workflow.",
  submit: "Create first subscription from this quote", submitting: "Submitting the original first-subscription intent…",
  pending: "A retained first-subscription attempt must be resolved before changing selections or requesting a replacement quote.",
  recovered: "The original request is not available in this session. Inspect authoritative subscription evidence or return to the original session; a new seed must not replace this attempt.",
  retry: "Retry the exact original seed", original: "Original first-subscription receipt",
  originalWarning: "This is the immutable original result, not the current subscription status, period, payment or readiness. Refresh the authoritative subscription and billing views before further actions.",
  subscription: "Original subscription ID", command: "Command ID", originalStatus: "Original status", originalPeriod: "Original trial period",
  creationReady: "The commercial subshape is available to the owning tenant-creation flow. No tenant has been created by this workspace.",
  failure: "The request did not produce a confirmed result.", requiredQuote: "Review a current quote before creating the first subscription.",
} as const;
const ar: { [K in keyof typeof en]: string } = {
  creation: "تسعير الاشتراك الأولي للمستأجر", seed: "أول اشتراك لمستأجر موجود",
  boundary: "تعرض التسعيرة تكلفة التطبيقات والإضافات المحددة. لا تنشئ مستأجرًا ولا تثبت جاهزية التثبيت أو تعيين المستخدمين.",
  selectedOnly: "راجع أعداد التطبيق والإضافات المحددة. تؤدي إزالة التطبيق إلى إزالة إضافاته المحددة أيضًا.",
  options: "قائمة التطبيقات والإضافات للاشتراك الأولي", loadOptions: "تحميل اختيارات الكتالوج الحالية", loadingOptions: "جارٍ تحميل اختيارات الكتالوج…",
  optionsBoundary: "هذه اختيارات منشورة بلا أسعار أو ضمان جاهزية التثبيت. يجب أن يتحقق الخادم من الاختيار الكامل بتسعيرة جديدة.",
  optionsForbidden: "يتطلب تحميل الاختيارات صلاحية إنشاء المستأجر. يمكن مراجعة الاختيارات المقدمة بصلاحية طلب التسعير.",
  optionsEmpty: "لم تُرجع القائمة الحالية أي تطبيقات.", chooseTier: "اختر باقة", addApplication: "إضافة التطبيق", addAddon: "إضافة الإضافة",
  selected: "محدد", blocked: "ملاحظات الكتالوج", incompatible: "اختر باقة أساسية متوافقة قبل اختيار هذه الإضافة.",
  changeTier: "لتغيير باقة محددة، أزل التطبيق وإضافاته ثم أضفه بالباقة المطلوبة.",
  cycle: "دورة الفوترة", monthly: "شهري", annual: "سنوي", trial: "أيام الفترة التجريبية", trialDefault: "اتركها فارغة ليطبق الخادم المدة المضبوطة لديه.",
  application: "التطبيق", tier: "الباقة", addon: "الإضافة", definition: "إصدار التعريف المحدد", baseSeats: "مقاعد التطبيق الأساسي", addonSeats: "مقاعد الإضافة",
  invalidSeats: "أدخل عددًا صحيحًا من 1 إلى 100000. لا يجوز أن تتجاوز مقاعد الإضافة مقاعد التطبيق الأساسي.",
  invalid: "راجع التطبيقات المحددة والأعداد ومدة الفترة التجريبية.", invalidTrial: "أدخل من 1 إلى 365 يومًا صحيحًا أو اتركها فارغة.",
  removeApplication: "إزالة التطبيق وإضافاته", removeAddon: "إزالة الإضافة", restore: "استعادة الاختيارات الأصلية",
  quote: "طلب تسعيرة من الخادم", quoting: "جارٍ طلب التسعيرة…", noQuote: "اطلب تسعيرة لعرض أسعار المستخدمين المتدرجة المعتمدة من الخادم.",
  expired: "انتهت صلاحية التسعيرة. اطلب تسعيرة جديدة قبل بدء أمر جديد.",
  base: "دورية التطبيقات بالدولار", addons: "دورية الإضافات بالدولار", combined: "الإجمالي الدوري بالدولار", seats: "المقاعد المسعّرة",
  allowance: "أعداد الإضافات لا تزيد عدد المستخدمين المسموح للتطبيق الأساسي.", resolvedTrial: "أيام التجربة التي حددها الخادم", expires: "انتهاء صلاحية التسعيرة", quoteId: "معرّف التسعيرة",
  brackets: "شرائح السعر الهامشية من الخادم", from: "من", through: "حتى", open: "بلا حد أعلى", charged: "المستخدمون المحتسبون", unit: "دولار لكل مستخدم", amount: "المبلغ بالدولار",
  forbidden: "الصلاحيات الحالية لا تسمح بطلب تسعيرة اشتراك أولي.", seedForbidden: "يتطلب إنشاء أول اشتراك صلاحيتَي إنشاء الاشتراك والإجراء الحرج معًا.",
  initialExists: "يوجد اشتراك مسجل. هذا المسار ليس لتعديل اشتراك قائم.",
  submit: "إنشاء أول اشتراك بهذه التسعيرة", submitting: "جارٍ إرسال طلب الاشتراك الأولي الأصلي…",
  pending: "يجب حسم محاولة الاشتراك الأولي المحفوظة قبل تغيير الاختيارات أو طلب تسعيرة بديلة.",
  recovered: "الطلب الأصلي غير متاح في هذه الجلسة. راجع بيانات الاشتراك المعتمدة أو ارجع للجلسة الأصلية؛ لا تستبدل هذه المحاولة بطلب إنشاء جديد.",
  retry: "إعادة طلب الاشتراك الأصلي نفسه", original: "إيصال إنشاء الاشتراك الأصلي",
  originalWarning: "هذه النتيجة الأصلية الثابتة، وليست حالة الاشتراك أو فترته أو مدفوعاته أو جاهزيته الحالية. حدّث بيانات الاشتراك والفوترة المعتمدة قبل أي إجراءات أخرى.",
  subscription: "معرّف الاشتراك الأصلي", command: "معرّف الأمر", originalStatus: "الحالة الأصلية", originalPeriod: "الفترة التجريبية الأصلية",
  creationReady: "الجزء التجاري متاح لمسار إنشاء المستأجر المالك. لم تنشئ هذه الواجهة أي مستأجر.",
  failure: "لم ينتج عن الطلب تأكيد معتمد.", requiredQuote: "راجع تسعيرة سارية قبل إنشاء أول اشتراك.",
};
export type InitialCommercialCopy = { [K in keyof typeof en]: string };
export const initialCommercialCopy = (locale: string): InitialCommercialCopy => locale === "ar" ? ar : en;
