export const commercialWorkspaceCopy = (lang: string) => lang === "ar" ? {
  title: "تعديل التطبيقات والإضافات", intro: "عدّل الاختيارات معاً، ثم حضّر العملية وراجع التسعيرة قبل تسوية المحفظة.",
  lifecycleUnavailable: "تعديل الخطة متاح فقط عندما يكون الاشتراك تجريبياً أو نشطاً.",
  seats: "المقاعد", tier: "الفئة", remove: "إزالة", restore: "استعادة", editCatalogue: "الفئات والإضافات", addApplication: "تحميل التطبيقات المتاحة", more: "تحميل المزيد",
  choose: "اختر فئة", useTier: "إضافة التطبيق أو تحديث فئته", loadAddons: "تحميل الإضافات المنشورة", addAddon: "إضافة إلى الاختيارات",
  unavailableAddon: "تتطلب هذه الإضافة مالكاً مسجلاً وتعريفاً منشوراً متوافقاً مع فئة التطبيق. لا يمكن إضافتها حالياً.",
  cataloguePermission: "عرض خيارات الفئات والإضافات يحتاج صلاحية قراءة الكتالوج.", noOptions: "لا توجد خيارات إضافية في هذه الصفحة.",
  invalid: "اختر تطبيقاً أساسياً واحداً على الأقل. يجب أن تكون المقاعد أعداداً صحيحة من 1 إلى 100000، وألا تتجاوز مقاعد الإضافة مقاعد التطبيق. الحد الأقصى 100 تعديل.",
  prepare: "تحضير التعديلات", price: "طلب تسعيرة جديدة", replayPreview: "استرجاع التسعيرة الأصلية", review: "راجعت جميع التعديلات والمبالغ المعروضة", apply: "تأكيد التسوية المراجعة",
  pending: "نتيجة الأمر السابق غير محسومة. أعد المحاولة بنفس الأمر أو اقرأ العملية قبل بدء تعديل آخر.", retry: "إعادة الأمر نفسه", retained: "الاختيارات المحفوظة لهذا الأمر", preparing: "جارٍ الاتصال بالخادم…",
  changed: "تغيرت مراجعة الاشتراك. اقرأ العملية الحالية وأكمل استعادتها، ثم ابدأ مسودة جديدة من أحدث اشتراك.", refresh: "قراءة الحالة والإيصال", newDraft: "بدء مسودة من الاشتراك الحالي",
  recovery: "استعادة العملية", reason: "سبب الاستعادة", reasonHint: "لا يُحفظ النص في المتصفح. عند إعادة أمر غير محسوم، أدخل السبب الأصلي نفسه.", reconcile: "إعادة التحقق والتوفيق", cancel: "طلب إلغاء التحضير",
  recoveryHint: "الإلغاء والتوفيق يخضعان لفحص الخادم لمراجعة العملية وحالتها الحالية.", operationId: "مرجع العملية", receiptId: "مرجع التسعيرة المسوّاة", readReceipt: "قراءة الإيصال الأصلي", lookup: "البحث عن عملية أو إيصال سابق",
  forbidden: "لا تملك صلاحية تنفيذ تعديل الاشتراك.", limited: "تبقى ترقية تعريف الإضافة غير متاحة. وقد يرفض الخادم تخفيض أو إزالة WebPhone لحين اكتمال متطلبات الحجز.", references: "مراجع الاختيار", previewNeeded: "بعد اكتمال التحضير، اطلب تسعيرة لمراجعة المبالغ الحالية.",
} : {
  title: "Change applications and addons", intro: "Edit the selections together, prepare the operation, then review the priced changes before wallet settlement.",
  lifecycleUnavailable: "Plan changes are available only while the subscription is in trial or active.",
  seats: "Seats", tier: "Tier", remove: "Remove", restore: "Restore", editCatalogue: "Tiers and addons", addApplication: "Load available applications", more: "Load more",
  choose: "Choose a tier", useTier: "Add application or update its tier", loadAddons: "Load published addons", addAddon: "Add to selections",
  unavailableAddon: "This addon needs a registered owner and a published definition compatible with the application tier. It cannot be added now.",
  cataloguePermission: "Viewing tier and addon options requires catalogue read permission.", noOptions: "There are no further options on this page.",
  invalid: "Keep at least one base application. Seats must be whole numbers from 1 to 100000, and addon seats must fit their parent application. Up to 100 changes are supported.",
  prepare: "Prepare changes", price: "Request fresh preview", replayPreview: "Restore original preview", review: "I reviewed all displayed changes and amounts", apply: "Confirm reviewed settlement",
  pending: "The previous command outcome is unresolved. Retry that same command or read its operation before starting another change.", retry: "Retry exact command", retained: "Retained selections for this command", preparing: "Contacting the server…",
  changed: "The subscription revision changed. Read and resolve the current operation, then start a draft from the latest subscription.", refresh: "Read progress and receipt", newDraft: "Start draft from current subscription",
  recovery: "Recover operation", reason: "Recovery reason", reasonHint: "This text is not stored in the browser. To retry an unresolved command, re-enter its exact original reason.", reconcile: "Reconcile operation", cancel: "Request preparation cancellation",
  recoveryHint: "The server checks the current operation state and revision before cancellation or reconciliation.", operationId: "Operation reference", receiptId: "Applied preview reference", readReceipt: "Read original receipt", lookup: "Find a previous operation or receipt",
  forbidden: "You do not have permission to change this subscription.", limited: "Addon definition adoption remains unavailable. The server may refuse WebPhone reduction or removal while its reservation prerequisites are incomplete.", references: "Selection references", previewNeeded: "Once preparation is complete, request a preview to review current amounts.",
};
