import { describe, expect, it } from "vitest";
import {
  createDatabaseServerInitialValues,
  credentialCheckLabel,
  DATABASE_ENGINE_REQUIREMENT,
  DATABASE_SERVER_CREATE_CONSTRAINTS,
  DATABASE_SECURITY_ADMIN_USERNAME_PATTERN,
  DATABASE_SECURITY_ADMIN_POSTURE,
  failedCredentialChecks,
  isDatabaseSecurityAdminStepValid,
  isDatabaseServerConnectionStepValid,
} from "./registration-state";

describe("database server registration state", () => {
  it("uses Core's non-TLS default instead of forcing SSL", () => {
    expect(createDatabaseServerInitialValues().sslMode).toBe("disable");
  });

  it("keeps the security-administrator failure detail", () => {
    const failed = failedCredentialChecks({
      connected: false,
      message: "One or more database credential checks failed.",
      checks: [
        {
          principal: "securityAdmin",
          connected: false,
          message: "password authentication failed",
        },
      ],
    });

    expect(failed).toEqual([
      {
        principal: "securityAdmin",
        connected: false,
        message: "password authentication failed",
      },
    ]);
  });

  it("labels the only credential accepted from the browser", () => {
    expect(credentialCheckLabel("securityAdmin")).toBe("Security admin");
  });

  it("states the exact supported PostgreSQL major", () => {
    expect(DATABASE_ENGINE_REQUIREMENT).toEqual({
      engine: "PostgreSQL",
      major: 16,
      label: "PostgreSQL major version 16 only",
    });
  });

  it("keeps the proven least-privilege PostgreSQL administrator posture exact", () => {
    expect(DATABASE_SECURITY_ADMIN_POSTURE).toEqual({
      requiredAttributes: ["LOGIN", "CREATEDB", "CREATEROLE"],
      rejectedAttributes: ["SUPERUSER", "REPLICATION", "BYPASSRLS"],
      membershipRule:
        "No unexpected membership may provide effective INHERIT or SET access. ADMIN-only membership edges to roles generated by Core are expected.",
      generatedPrincipals: [
        { principal: "mutakamel_provisioner", capability: "CREATEDB" },
        { principal: "mutakamel_backup", capability: "backup access" },
        {
          principal: "Application roles",
          capability: "manifest-scoped access",
        },
      ],
      readAllDataRule: "No pg_read_all_data grant is used.",
    });
  });

  it("keeps create constraints aligned with Core's DTO bounds", () => {
    expect(DATABASE_SERVER_CREATE_CONSTRAINTS).toEqual({
      name: { minLength: 1, maxLength: 120 },
      host: { minLength: 1, maxLength: 255 },
      port: { min: 1, max: 65_535 },
      maxTenants: { min: 1, max: 100_000 },
      securityAdminUsername: { minLength: 1, maxLength: 63 },
      securityAdminPassword: { minLength: 1, maxLength: 1_024 },
    });
  });

  it("rejects whitespace, non-integer, and out-of-range connection values", () => {
    expect(
      isDatabaseServerConnectionStepValid({
        name: "Primary",
        host: "postgres",
        port: 5432,
        maxTenants: 100,
      }),
    ).toBe(true);
    expect(
      isDatabaseServerConnectionStepValid({
        name: "   ",
        host: "postgres",
        port: 5432,
        maxTenants: 100,
      }),
    ).toBe(false);
    expect(
      isDatabaseServerConnectionStepValid({
        name: "Primary",
        host: "postgres",
        port: 54.32,
        maxTenants: 100_001,
      }),
    ).toBe(false);
  });

  it("validates the security-administrator username contract without trimming the password", () => {
    expect(
      isDatabaseSecurityAdminStepValid({
        username: "mutakamel_security_admin",
        password: " ",
      }),
    ).toBe(true);
    expect(
      isDatabaseSecurityAdminStepValid({ username: "   ", password: "secret" }),
    ).toBe(false);
    expect(
      isDatabaseSecurityAdminStepValid({
        username: "pg_security_admin",
        password: "secret",
      }),
    ).toBe(false);
    expect(
      isDatabaseSecurityAdminStepValid({
        username: "Security_Admin",
        password: "secret",
      }),
    ).toBe(false);
    expect(
      isDatabaseSecurityAdminStepValid({
        username: "1security_admin",
        password: "secret",
      }),
    ).toBe(false);
    expect(
      isDatabaseSecurityAdminStepValid({
        username: "security-admin",
        password: "secret",
      }),
    ).toBe(false);
    expect(
      isDatabaseSecurityAdminStepValid({
        username: `a${"x".repeat(63)}`,
        password: "secret",
      }),
    ).toBe(false);
    expect(
      isDatabaseSecurityAdminStepValid({
        username: "mutakamel_security_admin",
        password: "x".repeat(1_025),
      }),
    ).toBe(false);
  });

  it("uses Core's exact reserved-prefix PostgreSQL principal pattern", () => {
    expect(DATABASE_SECURITY_ADMIN_USERNAME_PATTERN.source).toBe(
      "^(?!pg_)[a-z_][a-z0-9_]{0,62}$",
    );
    expect(DATABASE_SECURITY_ADMIN_USERNAME_PATTERN.test("_security_admin")).toBe(true);
    expect(DATABASE_SECURITY_ADMIN_USERNAME_PATTERN.test("pg_admin")).toBe(false);
  });

});
