import type {
  CreateDatabaseServerDto,
  DatabaseServerConnectivityResult,
  DatabaseServerCredentialCheckName,
  DatabaseServerView,
} from "../types";

export const DATABASE_SECURITY_ADMIN_POSTURE = {
  requiredAttributes: ["LOGIN", "CREATEDB", "CREATEROLE"],
  rejectedAttributes: ["SUPERUSER", "REPLICATION", "BYPASSRLS"],
  membershipRule:
    "No unexpected membership may provide effective INHERIT or SET access. ADMIN-only membership edges to roles generated by Core are expected.",
  generatedPrincipals: [
    { principal: "mutakamel_provisioner", capability: "CREATEDB" },
    { principal: "mutakamel_backup", capability: "backup access" },
    { principal: "Application roles", capability: "manifest-scoped access" },
  ],
  readAllDataRule: "No pg_read_all_data grant is used.",
} as const;

export const DATABASE_ENGINE_REQUIREMENT = {
  engine: "PostgreSQL",
  major: 16,
  label: "PostgreSQL major version 16 only",
} as const;

export const DATABASE_SECURITY_ADMIN_USERNAME_PATTERN =
  /^(?!pg_)[a-z_][a-z0-9_]{0,62}$/u;

export const DATABASE_SERVER_CREATE_CONSTRAINTS = {
  name: { minLength: 1, maxLength: 120 },
  host: { minLength: 1, maxLength: 255 },
  port: { min: 1, max: 65_535 },
  maxTenants: { min: 1, max: 100_000 },
  securityAdminUsername: { minLength: 1, maxLength: 63 },
  securityAdminPassword: { minLength: 1, maxLength: 1_024 },
} as const;

export function isDatabaseServerConnectionStepValid(
  value: Pick<CreateDatabaseServerDto, "name" | "host" | "port" | "maxTenants">,
): boolean {
  const nameLength = value.name.trim().length;
  const hostLength = value.host.trim().length;
  const port = value.port;

  return (
    nameLength >= DATABASE_SERVER_CREATE_CONSTRAINTS.name.minLength &&
    nameLength <= DATABASE_SERVER_CREATE_CONSTRAINTS.name.maxLength &&
    hostLength >= DATABASE_SERVER_CREATE_CONSTRAINTS.host.minLength &&
    hostLength <= DATABASE_SERVER_CREATE_CONSTRAINTS.host.maxLength &&
    port !== undefined &&
    Number.isInteger(port) &&
    port >= DATABASE_SERVER_CREATE_CONSTRAINTS.port.min &&
    port <= DATABASE_SERVER_CREATE_CONSTRAINTS.port.max &&
    Number.isInteger(value.maxTenants) &&
    value.maxTenants >= DATABASE_SERVER_CREATE_CONSTRAINTS.maxTenants.min &&
    value.maxTenants <= DATABASE_SERVER_CREATE_CONSTRAINTS.maxTenants.max
  );
}

export function isDatabaseSecurityAdminStepValid(
  value: CreateDatabaseServerDto["securityAdminCredentials"],
): boolean {
  const username = value.username.trim();
  const usernameLength = username.length;
  const passwordLength = value.password.length;

  return (
    usernameLength >=
      DATABASE_SERVER_CREATE_CONSTRAINTS.securityAdminUsername.minLength &&
    usernameLength <=
      DATABASE_SERVER_CREATE_CONSTRAINTS.securityAdminUsername.maxLength &&
    DATABASE_SECURITY_ADMIN_USERNAME_PATTERN.test(username) &&
    passwordLength >=
      DATABASE_SERVER_CREATE_CONSTRAINTS.securityAdminPassword.minLength &&
    passwordLength <=
      DATABASE_SERVER_CREATE_CONSTRAINTS.securityAdminPassword.maxLength
  );
}

export function createDatabaseServerInitialValues(): CreateDatabaseServerDto {
  return {
    name: "",
    host: "",
    port: 5432,
    maxTenants: 100,
    securityAdminCredentials: { username: "", password: "" },
    sslMode: "disable",
    sslRejectUnauthorized: true,
    maintenanceDatabase: "postgres",
  };
}

const PRINCIPAL_LABELS: Record<DatabaseServerCredentialCheckName, string> = {
  securityAdmin: "Security admin",
};

export function credentialCheckLabel(
  principal: DatabaseServerCredentialCheckName,
): string {
  return PRINCIPAL_LABELS[principal];
}

export function failedCredentialChecks(
  result: DatabaseServerConnectivityResult,
) {
  return (result.checks ?? []).filter((check) => !check.connected);
}

export function needsActiveApplicationBindingBackfill(
  server: Pick<DatabaseServerView, "credentialBootstrap" | "systemPrincipals">,
  applicationBindingCount: number,
  bindingsSettled: boolean,
): boolean {
  return (
    bindingsSettled &&
    applicationBindingCount === 0 &&
    server.systemPrincipals.some(
      (binding) =>
        binding.purpose === "PROVISIONING" &&
        binding.databasePrincipal === "mutakamel_provisioner" &&
        binding.status === "READY",
    ) &&
    server.credentialBootstrap.totalPrincipals === 2 &&
    server.credentialBootstrap.readyPrincipals === 2 &&
    server.credentialBootstrap.status === "PENDING"
  );
}
