export type TenantWorkspaceLocale = "ar" | "en";

const copy = {
  en: {
    title: "Tenant control",
    loading: "Loading tenant…",
    forbidden: "You do not have permission to view this tenant.",
    destroyed: "The tenant was permanently destroyed.",
    retry: "Retry",
    profile: "Profile",
    save: "Save profile",
    reload: "Reload server version",
    stale: "This profile changed on the server. Review or reload before saving again.",
    lifecycle: "Lifecycle & provisioning",
    suspend: "Suspend",
    activate: "Activate",
    reprovision: "Retry provisioning",
    cancelProvisioning: "Cancel provisioning",
    softDelete: "Soft delete",
    destroy: "Destroy permanently",
    destroySubscriptions: "Also purge subscriptions",
    confirm: "Confirm",
    cancel: "Keep tenant",
    polling: "Provisioning is running. Status refreshes automatically.",
    pollExhausted: "Automatic status checks paused. Refresh to continue.",
    domains: "Domains",
    domainPlaceholder: "crm.example.com",
    validate: "Validate",
    addDomain: "Attach domain",
    primary: "Primary",
    secondary: "Secondary",
    remove: "Remove",
    promote: "Set primary",
    pendingDns: "The domain may be attached as pending while DNS is prepared.",
    clearAddress: "Clear address",
    noDomains: "No domain evidence is available.",
    correlation: "Correlation ID",
  },
  ar: {
    title: "إدارة المستأجر",
    loading: "جارٍ تحميل المستأجر…",
    forbidden: "لا تملك صلاحية عرض هذا المستأجر.",
    destroyed: "تم حذف المستأجر نهائيًا.",
    retry: "إعادة المحاولة",
    profile: "الملف التعريفي",
    save: "حفظ الملف",
    reload: "تحميل نسخة الخادم",
    stale: "تغيّر الملف على الخادم. راجع التغييرات أو أعد التحميل قبل الحفظ.",
    lifecycle: "دورة الحياة والتجهيز",
    suspend: "تعليق",
    activate: "تفعيل",
    reprovision: "إعادة محاولة التجهيز",
    cancelProvisioning: "إلغاء التجهيز",
    softDelete: "حذف قابل للاسترداد",
    destroy: "حذف نهائي",
    destroySubscriptions: "حذف الاشتراكات أيضًا",
    confirm: "تأكيد",
    cancel: "الإبقاء على المستأجر",
    polling: "التجهيز قيد التنفيذ. يتم تحديث الحالة تلقائيًا.",
    pollExhausted: "توقفت فحوص الحالة التلقائية. حدّث للمتابعة.",
    domains: "النطاقات",
    domainPlaceholder: "crm.example.com",
    validate: "فحص",
    addDomain: "إرفاق النطاق",
    primary: "أساسي",
    secondary: "ثانوي",
    remove: "إزالة",
    promote: "تعيين كأساسي",
    pendingDns: "يمكن إرفاق النطاق بحالة معلّقة أثناء إعداد DNS.",
    clearAddress: "مسح العنوان",
    noDomains: "لا تتوفر بيانات نطاقات.",
    correlation: "معرّف الارتباط",
  },
} as const;

export function tenantWorkspaceCopy(locale: TenantWorkspaceLocale) {
  return copy[locale];
}
