import type { CopyShape } from "@/i18n/copy-shape";

export type NotificationLanguage = "ar" | "en";

const en = {
  title: "Notification center",
  inbox: "Inbox",
  preferences: "Personal preferences",
  devices: "Push device token",
  runtime: "Effective runtime",
  unread: "Unread",
  all: "All notifications",
  unreadOnly: "Unread only",
  pageSize: "Page size",
  refresh: "Refresh",
  loadMore: "Load more",
  loading: "Loading notifications…",
  empty: "There are no notifications for this filter.",
  forbidden: "You do not have permission to read notifications.",
  readPermission: "Required permission: admin.notifications.read",
  managePermission: "Management actions require admin.notifications.manage.",
  unavailable: "The notification service is temporarily unavailable.",
  error: "Notifications could not be loaded.",
  contractDrift: "The server returned an unsupported notification response.",
  retry: "Retry",
  markRead: "Mark read",
  acknowledge: "Acknowledge",
  dismiss: "Dismiss",
  dismissConfirmTitle: "Dismiss this notification?",
  dismissConfirmDescription: "This removes the notification from your inbox. It does not delete the shared notification record.",
  revokeConfirmTitle: "Revoke this device token?",
  revokeConfirmDescription: "Push delivery to this exact registered device token will stop.",
  confirm: "Confirm",
  open: "Open destination",
  compatibility: "Compatibility aliases",
  acknowledgeLegacy: "Acknowledge via /ack alias",
  dismissLegacy: "Dismiss via POST alias",
  readAll: "Read all (canonical)",
  markAllReadLegacy: "Mark all read (compatibility alias)",
  updated: "Updated recipients",
  source: "Source",
  type: "Type",
  priority: "Priority",
  created: "Created",
  delivered: "Delivered",
  readAt: "Read",
  acknowledgedAt: "Acknowledged",
  channel: "Channels",
  configurePreference: "Configure one notification type",
  notificationType: "Notification type",
  notificationTypePlaceholder: "tenant.user.invited",
  inApp: "In-app",
  push: "Push",
  email: "Email",
  quietHours: "Quiet-hours JSON object",
  quietHoursHint: "Use an object such as {\"from\":\"22:00\",\"to\":\"07:00\",\"timezone\":\"Africa/Cairo\"}.",
  edit: "Edit",
  savePreference: "Save preference",
  saving: "Saving…",
  noPreferences: "No personal preferences are stored; system defaults apply.",
  provider: "Provider",
  deviceToken: "Provider token",
  tokenHint: "The token is sent once and cleared after a successful registration. It is never stored by this portal.",
  deviceId: "Device ID (optional)",
  platform: "Platform (optional)",
  enabled: "Enabled",
  enabledValue: "Enabled",
  disabledValue: "Disabled",
  register: "Register or refresh token",
  registering: "Registering…",
  receipt: "Latest safe registration receipt",
  tokenHash: "Token hash",
  tokenId: "Device token UUIDv7",
  revoke: "Revoke device token",
  revoking: "Revoking…",
  runtimeEnabled: "Notifications enabled",
  realtimeEnabled: "Realtime enabled",
  pushEnabled: "Push enabled",
  emailEnabled: "Email enabled",
  inAppEnabled: "In-app enabled",
  polling: "Polling interval",
  previewLimit: "Preview limit",
  runtimeProvider: "Effective provider",
  firebaseUnavailable: "Push remains unavailable until both the runtime flag and Firebase configuration are effective.",
  actionSucceeded: "The notification action completed.",
  preferenceSaved: "The preference was saved.",
  deviceRegistered: "The device token was registered.",
  deviceRevoked: "The device token was revoked.",
  bulkCompleted: "The bulk read action completed.",
  validationTitle: "Correct the highlighted input before submitting.",
  conflictTitle: "The request conflicts with newer server state. Refresh before retrying.",
  staleTitle: "The selected notification or device token is no longer actionable. Refresh the current state.",
  actionForbidden: "You no longer have permission to perform this notification action.",
  actionUnavailable: "The action outcome is unavailable. These naturally idempotent routes can be retried explicitly.",
  actionError: "The notification action failed.",
  errorCode: "Error code",
  correlation: "Correlation ID",
  pending: "Working…",
  close: "Close",
  viewAll: "View all notifications",
  newNotifications: "new",
  dropdownEmpty: "No notifications yet.",
  dropdownError: "Could not load notifications.",
  unknownTime: "Unknown time",
  validation: {
    required: "This field is required.",
    typeTooLong: "Notification type must be at most 128 characters.",
    invalidJson: "Quiet hours must be valid JSON.",
    objectRequired: "Quiet hours must be a JSON object.",
    tokenTooLong: "Provider token must be at most 4096 characters.",
    deviceIdTooLong: "Device ID must be at most 128 characters.",
    platformTooLong: "Platform must be at most 32 characters.",
    uuid: "Enter a canonical UUIDv7.",
  },
} as const;

const ar: CopyShape<typeof en> = {
  title: "مركز الإشعارات",
  inbox: "صندوق الوارد",
  preferences: "التفضيلات الشخصية",
  devices: "رمز جهاز الدفع",
  runtime: "إعداد التشغيل الفعلي",
  unread: "غير مقروء",
  all: "كل الإشعارات",
  unreadOnly: "غير المقروء فقط",
  pageSize: "حجم الصفحة",
  refresh: "تحديث",
  loadMore: "تحميل المزيد",
  loading: "جارٍ تحميل الإشعارات…",
  empty: "لا توجد إشعارات لهذا المرشح.",
  forbidden: "ليست لديك صلاحية قراءة الإشعارات.",
  readPermission: "الصلاحية المطلوبة: admin.notifications.read",
  managePermission: "تتطلب إجراءات الإدارة صلاحية admin.notifications.manage.",
  unavailable: "خدمة الإشعارات غير متاحة مؤقتًا.",
  error: "تعذر تحميل الإشعارات.",
  contractDrift: "أعاد الخادم استجابة إشعارات غير مدعومة.",
  retry: "إعادة المحاولة",
  markRead: "تحديد كمقروء",
  acknowledge: "إقرار",
  dismiss: "استبعاد",
  dismissConfirmTitle: "هل تريد استبعاد هذا الإشعار؟",
  dismissConfirmDescription: "يؤدي ذلك إلى إزالة الإشعار من صندوق واردك دون حذف سجل الإشعار المشترك.",
  revokeConfirmTitle: "هل تريد إلغاء رمز الجهاز هذا؟",
  revokeConfirmDescription: "سيتوقف تسليم إشعارات الدفع إلى رمز الجهاز المسجل المحدد.",
  confirm: "تأكيد",
  open: "فتح الوجهة",
  compatibility: "مسارات التوافق",
  acknowledgeLegacy: "الإقرار عبر المسار البديل ‎/ack",
  dismissLegacy: "الاستبعاد عبر مسار POST البديل",
  readAll: "قراءة الكل (المسار المعتمد)",
  markAllReadLegacy: "قراءة الكل (مسار التوافق)",
  updated: "المستلمون المحدّثون",
  source: "المصدر",
  type: "النوع",
  priority: "الأولوية",
  created: "تاريخ الإنشاء",
  delivered: "تم التسليم",
  readAt: "تمت القراءة",
  acknowledgedAt: "تم الإقرار",
  channel: "القنوات",
  configurePreference: "إعداد نوع إشعار واحد",
  notificationType: "نوع الإشعار",
  notificationTypePlaceholder: "tenant.user.invited",
  inApp: "داخل التطبيق",
  push: "دفع",
  email: "بريد إلكتروني",
  quietHours: "كائن JSON لساعات الهدوء",
  quietHoursHint: "استخدم كائنًا مثل {\"from\":\"22:00\",\"to\":\"07:00\",\"timezone\":\"Africa/Cairo\"}.",
  edit: "تعديل",
  savePreference: "حفظ التفضيل",
  saving: "جارٍ الحفظ…",
  noPreferences: "لا توجد تفضيلات شخصية محفوظة؛ تُطبّق الإعدادات الافتراضية.",
  provider: "المزوّد",
  deviceToken: "رمز المزوّد",
  tokenHint: "يُرسل الرمز مرة واحدة ويُمسح بعد نجاح التسجيل، ولا تخزّنه هذه البوابة.",
  deviceId: "معرّف الجهاز (اختياري)",
  platform: "المنصة (اختياري)",
  enabled: "مفعّل",
  enabledValue: "مفعّل",
  disabledValue: "غير مفعّل",
  register: "تسجيل الرمز أو تحديثه",
  registering: "جارٍ التسجيل…",
  receipt: "أحدث إيصال تسجيل آمن",
  tokenHash: "بصمة الرمز",
  tokenId: "UUIDv7 لرمز الجهاز",
  revoke: "إلغاء رمز الجهاز",
  revoking: "جارٍ الإلغاء…",
  runtimeEnabled: "الإشعارات مفعّلة",
  realtimeEnabled: "الوقت الفعلي مفعّل",
  pushEnabled: "الدفع مفعّل",
  emailEnabled: "البريد مفعّل",
  inAppEnabled: "داخل التطبيق مفعّل",
  polling: "فاصل الاستقصاء",
  previewLimit: "حد المعاينة",
  runtimeProvider: "المزوّد الفعلي",
  firebaseUnavailable: "يبقى الدفع غير متاح حتى تُفعّل علامة التشغيل وإعدادات Firebase معًا.",
  actionSucceeded: "اكتمل إجراء الإشعار.",
  preferenceSaved: "تم حفظ التفضيل.",
  deviceRegistered: "تم تسجيل رمز الجهاز.",
  deviceRevoked: "تم إلغاء رمز الجهاز.",
  bulkCompleted: "اكتمل إجراء القراءة الجماعي.",
  validationTitle: "صحّح الحقل المحدد قبل الإرسال.",
  conflictTitle: "يتعارض الطلب مع حالة أحدث على الخادم. حدّث قبل إعادة المحاولة.",
  staleTitle: "لم يعد الإشعار أو رمز الجهاز قابلاً للإجراء. حدّث الحالة الحالية.",
  actionForbidden: "لم تعد لديك صلاحية تنفيذ إجراء الإشعارات هذا.",
  actionUnavailable: "نتيجة الإجراء غير متاحة. يمكن إعادة محاولة هذه المسارات المتكررة بأمان بشكل صريح.",
  actionError: "فشل إجراء الإشعار.",
  errorCode: "رمز الخطأ",
  correlation: "معرّف الارتباط",
  pending: "جارٍ التنفيذ…",
  close: "إغلاق",
  viewAll: "عرض كل الإشعارات",
  newNotifications: "جديد",
  dropdownEmpty: "لا توجد إشعارات بعد.",
  dropdownError: "تعذر تحميل الإشعارات.",
  unknownTime: "وقت غير معروف",
  validation: {
    required: "هذا الحقل مطلوب.",
    typeTooLong: "يجب ألا يتجاوز نوع الإشعار 128 حرفًا.",
    invalidJson: "يجب أن تكون ساعات الهدوء JSON صالحًا.",
    objectRequired: "يجب أن تكون ساعات الهدوء كائن JSON.",
    tokenTooLong: "يجب ألا يتجاوز رمز المزوّد 4096 حرفًا.",
    deviceIdTooLong: "يجب ألا يتجاوز معرّف الجهاز 128 حرفًا.",
    platformTooLong: "يجب ألا تتجاوز المنصة 32 حرفًا.",
    uuid: "أدخل UUIDv7 قياسيًا.",
  },
};

export type NotificationsCopy = CopyShape<typeof en>;

export function getNotificationsCopy(language: NotificationLanguage): NotificationsCopy {
  return language === "ar" ? ar : en;
}
