"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, FileKey2, Loader2, Save } from "lucide-react";
import { useI18n } from "@/i18n/I18nContext";
import { useReleaseDraftDetail } from "../hooks/use-release-draft-detail";
import { ReleaseDefinitionFields } from "./release-definition-form";
import { formatDate, JsonEvidence, RELEASE_COPY, RefreshReleaseButton, ReleaseFieldError, ReleaseMutationNotice, ReleasePageFrame, ReleaseSnapshotMeta, ReleaseStatePanel, StatusBadge, type ReleaseCopy } from "./release-shared";

export function ReleaseDraftDetailScreen({ draftId }: { draftId: string }) {
  const { lang, dir } = useI18n();
  const copy = RELEASE_COPY[lang];
  const detail = useReleaseDraftDetail(draftId);
  return <ReleasePageFrame dir={dir}><BackLink dir={dir} copy={copy} /><DraftBody detail={detail} copy={copy} lang={lang} /></ReleasePageFrame>;
}

function DraftBody({ detail, copy, lang }: { detail: ReturnType<typeof useReleaseDraftDetail>; copy: ReleaseCopy; lang: "ar" | "en" }) {
  if (detail.state === "LOADING") return <ReleaseStatePanel kind="loading" title={copy.loading} copy={copy} />;
  if (detail.state === "FORBIDDEN") return <ReleaseStatePanel kind="forbidden" title={copy.forbidden} detail={copy.readPermission} copy={copy} />;
  if (detail.state === "NOT_FOUND") return <ReleaseStatePanel kind="notFound" title={copy.notFound} detail={detail.error?.message} correlationId={detail.error?.correlationId} copy={copy} />;
  if (detail.state === "UNAVAILABLE") return <ReleaseStatePanel kind="unavailable" title={copy.unavailable} detail={detail.error?.message} correlationId={detail.error?.correlationId} copy={copy} action={<RefreshReleaseButton label={copy.retry} onClick={detail.refresh} />} />;
  if (detail.state === "ERROR" || !detail.snapshot) return <ReleaseStatePanel kind="error" title={copy.error} detail={detail.error?.message} correlationId={detail.error?.correlationId} copy={copy} action={<RefreshReleaseButton label={copy.retry} onClick={detail.refresh} />} />;
  const draft = detail.snapshot.data;
  const pending = detail.mutation.phase === "PENDING";
  return <div className="space-y-4" aria-busy={pending || detail.isRefreshing}><header className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-3"><h1 dir="ltr" className="font-mono text-xl font-black text-start">{draft.releaseVersion}</h1><StatusBadge status={draft.status} /></div><code dir="ltr" className="mt-2 block break-all text-start text-xs text-slate-500">{draft.draftId}</code></div><RefreshReleaseButton label={copy.refresh} onClick={detail.refresh} pending={detail.isRefreshing} /></div></header><ReleaseMutationNotice mutation={detail.mutation} copy={copy} />{detail.published ? <section role="status" className="rounded-xl border border-emerald-300 bg-emerald-50 p-4 text-emerald-950 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-100"><h2 className="font-black">{copy.published}</h2><Link href={`/provisioning/releases/${detail.published.data.releaseId}`} className="mt-3 inline-flex min-h-11 items-center rounded-xl bg-emerald-800 px-4 text-sm font-black text-white">{copy.viewPublished}</Link></section> : null}<EvidenceGrid draft={draft} copy={copy} lang={lang} />{detail.canEdit ? <form aria-label={copy.definition} onSubmit={(event) => { event.preventDefault(); void detail.saveDraft(); }} className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-black">{copy.definition}</h2><p className="text-sm leading-6 text-slate-600 dark:text-slate-300">{copy.disclosurePolicy}</p><ReleaseDefinitionFields value={detail.definition} errors={detail.definitionErrors} copy={copy} onChange={detail.updateDefinition} disabled={pending} /><div className="flex justify-end"><button type="submit" disabled={pending} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-cyan-700 px-5 text-sm font-black text-white disabled:opacity-50">{pending && detail.mutation.name === "UPDATE" ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}{pending && detail.mutation.name === "UPDATE" ? copy.saving : copy.saveDraft}</button></div></form> : <ManifestEvidence draft={draft} copy={copy} />}{draft.status === "DRAFT" && detail.permissions.canManageDrafts ? <ValidationForm detail={detail} copy={copy} /> : null}{draft.status === "VALIDATED" ? <PublishForm detail={detail} copy={copy} /> : null}{draft.status === "PUBLISHED" && draft.publishedReleaseId ? <Link href={`/provisioning/releases/${draft.publishedReleaseId}`} className="inline-flex min-h-11 items-center rounded-xl bg-emerald-800 px-4 text-sm font-black text-white">{copy.viewPublished}</Link> : null}<ReleaseSnapshotMeta snapshot={detail.snapshot} copy={copy} lang={lang} /></div>;
}

function ValidationForm({ detail, copy }: { detail: ReturnType<typeof useReleaseDraftDetail>; copy: ReleaseCopy }) {
  const pending = detail.mutation.phase === "PENDING";
  const errorId = "publisher-key-id-error";
  return <form aria-label={copy.validationTitle} onSubmit={(event) => { event.preventDefault(); void detail.validateDraft(); }} className="space-y-4 rounded-2xl border border-cyan-200 bg-cyan-50 p-5 dark:border-cyan-900 dark:bg-cyan-950/20"><div><h2 className="text-lg font-black">{copy.validationTitle}</h2><p className="mt-1 text-sm leading-6 text-slate-600 dark:text-slate-300">{copy.validationHelp}</p></div>{detail.definitionDirty ? <p role="alert" className="rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm font-bold text-amber-950 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-100">{copy.unsavedDefinition}</p> : null}<label htmlFor="publisher-key-id" className="grid max-w-2xl gap-1.5 text-xs font-bold"><span>{copy.publisherKeyId}</span><input id="publisher-key-id" dir="ltr" value={detail.publisherKeyId} aria-invalid={Boolean(detail.validationErrors.publisherKeyId)} aria-describedby={detail.validationErrors.publisherKeyId ? errorId : undefined} onChange={(event) => detail.setPublisherKeyId(event.target.value)} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3 font-mono text-sm text-slate-950 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100" /><ReleaseFieldError id={errorId} code={detail.validationErrors.publisherKeyId} copy={copy} /></label><button type="submit" disabled={!detail.canValidate || pending} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-cyan-700 px-5 text-sm font-black text-white disabled:opacity-50">{pending && detail.mutation.name === "VALIDATE" ? <Loader2 className="size-4 animate-spin" /> : <CheckCircle2 className="size-4" />}{pending && detail.mutation.name === "VALIDATE" ? copy.validating : copy.validate}</button></form>;
}

function PublishForm({ detail, copy }: { detail: ReturnType<typeof useReleaseDraftDetail>; copy: ReleaseCopy }) {
  const pending = detail.mutation.phase === "PENDING";
  const signatureError = "release-signature-error";
  return <section className="space-y-4 rounded-2xl border border-amber-300 bg-amber-50 p-5 dark:border-amber-900 dark:bg-amber-950/20"><div><h2 className="text-lg font-black">{copy.publishTitle}</h2><p className="mt-1 text-sm leading-6 text-slate-600 dark:text-slate-300">{copy.publishHelp}</p></div><SigningPayload detail={detail} copy={copy} />{detail.definitionDirty ? <p role="alert" className="rounded-xl border border-amber-400 bg-white/70 p-3 text-sm font-bold text-amber-950 dark:border-amber-800 dark:bg-slate-950/40 dark:text-amber-100">{copy.unsavedDefinition}</p> : null}{!detail.permissions.canPublishCritical ? <ReleaseStatePanel kind="forbidden" title={copy.commandForbidden} detail="admin.provisioning.releases.publish + admin.provisioning.critical" copy={copy} /> : <form aria-label={copy.publishTitle} onSubmit={(event) => { event.preventDefault(); void detail.publish(); }} className="space-y-4"><label htmlFor="release-signature" className="grid gap-1.5 text-xs font-bold"><span>{copy.signatureBase64}</span><textarea id="release-signature" dir="ltr" spellCheck={false} rows={4} value={detail.publishDraft.signatureBase64} aria-invalid={Boolean(detail.publishErrors.signatureBase64)} aria-describedby={detail.publishErrors.signatureBase64 ? signatureError : undefined} onChange={(event) => detail.updatePublishDraft("signatureBase64", event.target.value)} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-start font-mono text-xs text-slate-950 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100" /><ReleaseFieldError id={signatureError} code={detail.publishErrors.signatureBase64} copy={copy} /></label><label className="flex items-start gap-3 rounded-xl border border-amber-300 bg-white/60 p-3 text-sm font-bold dark:border-amber-900 dark:bg-slate-950/40"><input type="checkbox" checked={detail.publishDraft.confirmed} aria-invalid={Boolean(detail.publishErrors.confirmed)} aria-describedby={detail.publishErrors.confirmed ? "publish-confirm-error" : undefined} onChange={(event) => detail.updatePublishDraft("confirmed", event.target.checked)} className="mt-1 size-4 accent-amber-700" /><span>{copy.publishConfirm}</span></label><ReleaseFieldError id="publish-confirm-error" code={detail.publishErrors.confirmed} copy={copy} /><button type="submit" disabled={!detail.canPublish || pending} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-amber-700 px-5 text-sm font-black text-white disabled:opacity-50">{pending && detail.mutation.name === "PUBLISH" ? <Loader2 className="size-4 animate-spin" /> : <FileKey2 className="size-4" />}{pending && detail.mutation.name === "PUBLISH" ? copy.publishing : copy.publish}</button></form>}</section>;
}

function SigningPayload({ detail, copy }: { detail: ReturnType<typeof useReleaseDraftDetail>; copy: ReleaseCopy }) {
  if (detail.signingEvidence.phase === "CHECKING") return <p role="status" className="text-sm">{copy.payloadChecking}</p>;
  if (detail.signingEvidence.phase === "UNAVAILABLE") return <p role="alert" className="text-sm font-bold text-rose-700 dark:text-rose-300">{copy.payloadUnavailable}</p>;
  if (detail.signingEvidence.phase === "MISMATCH") return <p role="alert" className="text-sm font-bold text-rose-700 dark:text-rose-300">{copy.payloadMismatch}</p>;
  if (detail.signingEvidence.phase !== "VERIFIED") return null;
  return <label className="grid gap-1.5 text-xs font-bold"><span>{copy.payloadBase64}</span><textarea readOnly dir="ltr" rows={6} value={detail.signingEvidence.payloadBase64} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-start font-mono text-xs text-slate-100" /></label>;
}

function EvidenceGrid({ draft, copy, lang }: { draft: NonNullable<ReturnType<typeof useReleaseDraftDetail>["snapshot"]>["data"]; copy: ReleaseCopy; lang: "ar" | "en" }) {
  return <div className="grid gap-4 xl:grid-cols-3"><EvidenceCard title={copy.lifecycleEvidence}><Evidence label={copy.revision} value={String(draft.revision)} /><Evidence label={copy.createdAt} value={formatDate(draft.createdAt, lang)} /><Evidence label={copy.updatedAt} value={formatDate(draft.updatedAt, lang)} /><Evidence label={copy.validatedAt} value={formatDate(draft.validatedAt, lang)} /></EvidenceCard><EvidenceCard title={copy.manifestEvidence}><Evidence label={copy.componentId} value={draft.componentId} mono /><Evidence label={copy.manifestChecksumLabel} value={draft.manifestChecksum} mono /><Evidence label={copy.schemaChecksum} value={draft.schemaChecksum ?? "—"} mono /></EvidenceCard><EvidenceCard title={copy.signatureEvidence}><Evidence label={copy.publisherKeyId} value={draft.publisherKeyId ?? "—"} mono /><Evidence label={copy.signingDigest} value={draft.signingDigest ?? "—"} mono /><Evidence label={copy.publishedReleaseId} value={draft.publishedReleaseId ?? "—"} mono /></EvidenceCard></div>;
}

function ManifestEvidence({ draft, copy }: { draft: NonNullable<ReturnType<typeof useReleaseDraftDetail>["snapshot"]>["data"]; copy: ReleaseCopy }) { return <section className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p className="text-sm text-slate-600 dark:text-slate-300">{copy.disclosurePolicy}</p><div className="grid gap-3 xl:grid-cols-2"><JsonEvidence title={copy.manifestPayload} value={draft.manifestPayload} /><JsonEvidence title={copy.compatibility} value={draft.compatibility} /></div></section>; }
function EvidenceCard({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-black">{title}</h2><dl className="mt-3 grid gap-2">{children}</dl></section>; }
function Evidence({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div className="rounded-xl bg-slate-100 px-3 py-2 dark:bg-slate-800/70"><dt className="text-xs font-bold text-slate-500">{label}</dt><dd dir={mono ? "ltr" : undefined} className={`mt-1 break-all text-sm font-bold ${mono ? "text-start font-mono" : ""}`}>{value}</dd></div>; }
function BackLink({ dir, copy }: { dir: "rtl" | "ltr"; copy: ReleaseCopy }) { return <Link href="/provisioning/releases" className="inline-flex min-h-10 items-center gap-2 text-sm font-bold text-slate-600 hover:text-cyan-700 dark:text-slate-300">{dir === "rtl" ? <ArrowRight className="size-4" /> : <ArrowLeft className="size-4" />}{copy.back}</Link>; }
