const en = {
  ownerUnavailable: "Publication, feature grants, component bindings and configuration schemas require a registered addon implementation for this application. Draft details, tier compatibility and prices can still be managed.",
  title: "Application addons", description: "Dependent extensions with their own per-user pricing. Buying seats, company/branch activation and user assignment are separate steps.",
  create: "Create addon", name: "Name", key: "Immutable key", descriptionLabel: "Description", search: "Search addons", refresh: "Refresh", loading: "Loading…",
  empty: "No addons match this application.", forbidden: "Addon-read permission is required.", failed: "Unable to load current addon evidence.", previous: "Previous", next: "Next",
  definition: "Definition", pricing: "Per-user pricing", versions: "Published versions", audit: "Audit", draft: "Draft", published: "Published", noDraft: "No editable draft.",
  unpublished: "Not published", edit: "Edit draft", clone: "Create draft from published", publish: "Publish draft", deprecate: "Deprecate", disable: "Disable", remove: "Delete draft", revoke: "Revoke version",
  lifecycle: "Lifecycle", catalogueRevision: "Catalogue revision", operationalRevision: "Operational revision", definitionRevision: "Definition revision",
  boundary: "Publication does not adopt this definition for existing subscriptions or prove runtime readiness. Existing accepted definitions and prices stay pinned.",
  saved: "Command accepted. Current evidence was requested again.", pending: "Canonical command accepted. Worker convergence is still pending; this is not fleet completion.",
  retry: "Retry exact command", unknown: "Outcome unresolved. Keep the original values for an exact retry. Changed requests are blocked until this command is resolved.",
  recovered: "A pending command survived reload. Re-enter the exact original action and values to reuse its key; do not start a replacement operation.",
  close: "Close", cancel: "Cancel", save: "Save", reason: "Audited reason", confirm: "Confirm action", invalid: "Check the highlighted fields.", required: "This field is required.",
  keyInvalid: "Use the owning app prefix and a lowercase addon key, for example crm.logistics.", reasonHint: "1–256 characters. No credentials or personal financial details.",
  currentVsDraft: "Published and draft snapshots", version: "Version", noHistory: "No published history.", view: "View snapshot", noAudit: "No audit events.", actor: "Actor", action: "Action", occurred: "Occurred at",
  compatibility: "Tier compatibility", allActive: "All active tiers", allowlist: "Explicit tier allowlist", tierIds: "Tier IDs", grants: "Feature grants", featureIds: "Feature IDs",
  parentTiers: "Parent application tiers", parentTiersHint: "Select active tiers from this application. The server validates compatibility when you confirm.",
  loadingTiers: "Loading parent application tiers…", refreshTiers: "Reload tier labels", noActiveTiers: "This application has no active tiers available to select.",
  tiersFailed: "Tier labels could not be loaded. You can retry the lookup or enter the existing IDs manually.",
  unavailableTiers: "These selected IDs are inactive, deleted or absent from the current parent-tier list. They are preserved below; remove them explicitly before confirming.",
  unknownTier: "Selected tier unavailable", manualTiers: "Tier labels are unavailable. Enter existing tier IDs from this application; the server validates each ID.",
  bindings: "Component bindings", dependencies: "Application dependencies", schema: "Registered schema reference", schemaOwner: "Schema owner application ID", schemaKey: "Schema key", schemaVersion: "Schema version", checksum: "SHA-256 checksum",
  editCompatibility: "Edit compatibility", editGrants: "Edit feature grants", editBindings: "Edit bindings", editSchema: "Edit schema reference", linesHint: "One existing UUID per line. Values are checked by the owning service.",
  bindingsHint: "One binding per line: component UUID, release UUID, capability key. Only registered capabilities are accepted.",
  dependenciesHint: "One dependency per line: application UUID, optional addon UUID, optional minimum definition UUID.",
  grantsOpaque: "This definition has owner-specific feature configuration. Generic editing is unavailable; use a registered typed owner editor to preserve it.",
  referenceOnly: "Only an immutable registered schema identity is accepted. No arbitrary schema URL or executable configuration.",
  monthly: "Monthly", annual: "Annual", cycle: "Billing cycle", unconfigured: "Not configured — unavailable, not free", configured: "Configured", priceRevision: "Price revision",
  priceHint: "Graduated USD price per user for each bracket. Monthly and annual ladders are independent. New prices do not rewrite accepted subscription or invoice history.",
  priceReadRequired: "Your cycle drafts are retained. Refresh the addon successfully before editing or saving prices.",
  priceHeadChanged: "This cycle has a newer stored revision. Your unsaved values and reviewed revision are retained. Loading the latest cycle discards this cycle's edits and reason only.",
  loadLatestCycle: "Discard this cycle's edits and load latest",
  min: "From users", max: "Through users", price: "USD / user", openEnded: "No upper limit", addBracket: "Add bracket", removeBracket: "Remove bracket", savePrices: "Save price ladder",
  ladderInvalid: "Use 1–100 contiguous brackets starting at 1, with only the final bracket open-ended. Prices must be non-negative USD strings with up to 14 integer and 4 decimal digits.",
  quoteUnavailable: "An authoritative sample quote is not available on this Admin API. This editor does not calculate or approve subscription charges.",
  lifecycleWarning: "Review the target and current revision. Disabling or revoking denies operational authority; it does not automatically refund money. Published history cannot be deleted.",
  publishWarning: "This seals the current draft. The server verifies owner registration, compatibility and release pins. It does not enable customer seats or migrate tenants.",
  systemBoundary: "System and non-billable applications cannot own paid addons.", emptySnapshot: "No snapshot", none: "None", pendingDraft: "Draft edits do not replace the published snapshot.",
  stale: "The stored revision changed. Refresh and review the latest evidence, then explicitly confirm again.",
  activeLabel: "Active", deprecatedLabel: "Deprecated", disabledLabel: "Disabled", changed: "Changed",
} as const;
const ar: { [K in keyof typeof en]: string } = {
  ownerUnavailable: "النشر ومنح الخصائص وروابط المكونات ومخططات الإعدادات تتطلب تنفيذ إضافة مسجلًا لهذا التطبيق. يظل تعديل بيانات المسودة وتوافق الباقات والأسعار متاحًا.",
  title: "إضافات التطبيق", description: "إضافات تابعة للتطبيق بتسعير مستقل لكل مستخدم. شراء المقاعد وتفعيل الشركة/الفرع وتعيين المستخدم خطوات منفصلة.",
  create: "إنشاء إضافة", name: "الاسم", key: "المفتاح الثابت", descriptionLabel: "الوصف", search: "البحث في الإضافات", refresh: "تحديث", loading: "جارٍ التحميل…",
  empty: "لا توجد إضافات مطابقة لهذا التطبيق.", forbidden: "صلاحية قراءة الإضافات مطلوبة.", failed: "تعذر تحميل بيانات الإضافة الحالية.", previous: "السابق", next: "التالي",
  definition: "التعريف", pricing: "التسعير لكل مستخدم", versions: "الإصدارات المنشورة", audit: "سجل التدقيق", draft: "المسودة", published: "المنشور", noDraft: "لا توجد مسودة قابلة للتعديل.",
  unpublished: "غير منشور", edit: "تعديل المسودة", clone: "إنشاء مسودة من المنشور", publish: "نشر المسودة", deprecate: "إيقاف الاختيارات الجديدة", disable: "تعطيل", remove: "حذف المسودة", revoke: "إلغاء صلاحية الإصدار",
  lifecycle: "حالة دورة الحياة", catalogueRevision: "مراجعة الكتالوج", operationalRevision: "المراجعة التشغيلية", definitionRevision: "مراجعة التعريف",
  boundary: "النشر لا يعتمد التعريف للاشتراكات الحالية ولا يثبت الجاهزية التشغيلية. تظل التعريفات والأسعار المقبولة مرتبطة بإصداراتها.",
  saved: "تم قبول العملية وإعادة طلب البيانات الحالية.", pending: "تم قبول العملية الأساسية. مزامنة الـ Worker ما زالت معلقة؛ لا يعني ذلك اكتمال التحديث على كل الخدمات.",
  retry: "إعادة نفس الطلب", unknown: "نتيجة الطلب غير محسومة. احتفظ بالقيم الأصلية لإعادة نفس الطلب. الطلبات المختلفة محظورة حتى حسم هذه العملية.",
  recovered: "تم استرجاع طلب معلق بعد إعادة التحميل. أدخل نفس الإجراء والقيم الأصلية لإعادة استخدام مفتاحه؛ لا تبدأ عملية بديلة.",
  close: "إغلاق", cancel: "إلغاء", save: "حفظ", reason: "سبب الإجراء المسجل", confirm: "تأكيد الإجراء", invalid: "راجع الحقول الموضحة.", required: "هذا الحقل مطلوب.",
  keyInvalid: "استخدم بادئة التطبيق ومفتاح إضافة بحروف إنجليزية صغيرة، مثل crm.logistics.", reasonHint: "من 1 إلى 256 حرفًا. لا تكتب بيانات دخول أو تفاصيل مالية شخصية.",
  currentVsDraft: "مقارنة المنشور بالمسودة", version: "الإصدار", noHistory: "لا توجد إصدارات منشورة.", view: "عرض التعريف", noAudit: "لا توجد أحداث تدقيق.", actor: "المنفذ", action: "الإجراء", occurred: "وقت التنفيذ",
  compatibility: "توافق الباقات", allActive: "كل الباقات النشطة", allowlist: "قائمة باقات محددة", tierIds: "معرّفات الباقات", grants: "منح الخصائص", featureIds: "معرّفات الخصائص",
  parentTiers: "باقات التطبيق المالك", parentTiersHint: "اختر الباقات النشطة لهذا التطبيق. يتحقق الخادم من التوافق عند التأكيد.",
  loadingTiers: "جارٍ تحميل باقات التطبيق المالك…", refreshTiers: "إعادة تحميل أسماء الباقات", noActiveTiers: "لا توجد باقات نشطة متاحة للاختيار في هذا التطبيق.",
  tiersFailed: "تعذر تحميل أسماء الباقات. يمكنك إعادة المحاولة أو إدخال المعرّفات الموجودة يدويًا.",
  unavailableTiers: "هذه المعرّفات المحددة غير نشطة أو محذوفة أو غير موجودة في قائمة باقات التطبيق الحالية. تم الاحتفاظ بها أدناه؛ أزلها صراحةً قبل التأكيد.",
  unknownTier: "الباقة المحددة غير متاحة", manualTiers: "أسماء الباقات غير متاحة. أدخل معرّفات باقات موجودة لهذا التطبيق؛ يتحقق الخادم من كل معرّف.",
  bindings: "روابط المكونات", dependencies: "اعتماديات التطبيقات", schema: "مرجع مخطط مسجل", schemaOwner: "معرّف التطبيق المالك للمخطط", schemaKey: "مفتاح المخطط", schemaVersion: "إصدار المخطط", checksum: "بصمة SHA-256",
  editCompatibility: "تعديل التوافق", editGrants: "تعديل منح الخصائص", editBindings: "تعديل الروابط", editSchema: "تعديل مرجع المخطط", linesHint: "معرّف UUID موجود في كل سطر. يتحقق الخادم المالك من القيم.",
  bindingsHint: "رابط في كل سطر: معرّف المكون، معرّف الإصدار، مفتاح القدرة؛ بفواصل إنجليزية. تُقبل القدرات المسجلة فقط.",
  dependenciesHint: "اعتمادية في كل سطر: معرّف التطبيق، معرّف إضافة اختياري، معرّف الحد الأدنى للتعريف اختياري؛ بفواصل إنجليزية.",
  grantsOpaque: "يتضمن هذا التعريف إعدادات خصائص خاصة بالمالك. التعديل العام غير متاح؛ يلزم محرر مسجل يحافظ على إعداداتها.",
  referenceOnly: "يُقبل مرجع مخطط مسجل وثابت فقط. لا روابط مخططات عشوائية أو إعدادات تنفيذية.",
  monthly: "شهري", annual: "سنوي", cycle: "دورة الفوترة", unconfigured: "غير مُعد — غير متاح وليس مجانيًا", configured: "مُعد", priceRevision: "مراجعة السعر",
  priceHint: "سعر متدرج بالدولار لكل مستخدم داخل كل شريحة. التسعير الشهري والسنوي مستقلان. الأسعار الجديدة لا تعيد كتابة سجل الاشتراكات أو الفواتير المقبولة.",
  priceReadRequired: "تم الاحتفاظ بمسودات الدورات. حدّث بيانات الإضافة بنجاح قبل تعديل الأسعار أو حفظها.",
  priceHeadChanged: "توجد مراجعة محفوظة أحدث لهذه الدورة. تم الاحتفاظ بالقيم غير المحفوظة والمراجعة التي راجعتها. تحميل أحدث دورة يتجاهل تعديلات هذه الدورة وسببها فقط.",
  loadLatestCycle: "تجاهل تعديلات هذه الدورة وحمّل الأحدث",
  min: "من مستخدم", max: "حتى مستخدم", price: "دولار / مستخدم", openEnded: "بلا حد أعلى", addBracket: "إضافة شريحة", removeBracket: "حذف الشريحة", savePrices: "حفظ شرائح الأسعار",
  ladderInvalid: "استخدم من 1 إلى 100 شريحة متصلة تبدأ من 1، والشريحة الأخيرة وحدها مفتوحة. السعر غير سالب بحد أقصى 14 خانة صحيحة و4 عشرية.",
  quoteUnavailable: "لا توفر واجهة الإدارة هذه تسعيرة تجريبية معتمدة من الخادم. هذا المحرر لا يحسب أو يعتمد رسوم الاشتراكات.",
  lifecycleWarning: "راجع الهدف والمراجعة الحالية. التعطيل أو إلغاء صلاحية الإصدار يمنع الاستخدام التشغيلي ولا يرد الأموال تلقائيًا. لا يمكن حذف التاريخ المنشور.",
  publishWarning: "سيتم تثبيت المسودة الحالية. يتحقق الخادم من تسجيل المالك وتوافق الباقات وروابط الإصدارات. لا يفعّل مقاعد العملاء أو يرحّل بياناتهم.",
  systemBoundary: "تطبيقات النظام والتطبيقات غير القابلة للفوترة لا يمكنها امتلاك إضافات مدفوعة.", emptySnapshot: "لا يوجد تعريف", none: "لا يوجد", pendingDraft: "تعديلات المسودة لا تستبدل التعريف المنشور.",
  stale: "تغيّرت المراجعة المحفوظة. حدّث البيانات وراجعها ثم أكّد الإجراء من جديد.",
  activeLabel: "نشط", deprecatedLabel: "متوقف للاختيارات الجديدة", disabledLabel: "معطل", changed: "معدّل",
};
export function addonCopy(lang: string): { [K in keyof typeof en]: string } { return lang === "ar" ? ar : en; }
export type AddonCopy = ReturnType<typeof addonCopy>;
