export type TenantAccessLocale = "ar" | "en";

const en = {
  title: "Users & access",
  subtitle: "Tenant identities, roles, and lifecycle",
  notReady: "Users become available after the tenant database is ready.",
  forbidden: "You do not have permission to view tenant users.",
  retry: "Retry",
  invite: "Invite user",
  search: "Search users",
  apply: "Apply filters",
  clear: "Clear",
  allStatuses: "All statuses",
  activeRows: "Current users",
  deletedRows: "Deleted users",
  allRows: "All users",
  allRoles: "All roles",
  allBranches: "All branches",
  allDepartments: "All departments",
  allTeams: "All teams",
  name: "Name",
  email: "Email",
  organization: "Organization",
  roles: "Roles",
  status: "Status",
  actions: "Actions",
  owner: "Tenant owner",
  noUsers: "No users match these filters.",
  page: "Page",
  of: "of",
  previous: "Previous",
  next: "Next",
  total: "Total",
  invited: "Invited",
  active: "Active",
  suspended: "Suspended",
  deactivated: "Deactivated",
  deleted: "Deleted",
  locked: "Locked",
  details: "User details",
  close: "Close",
  edit: "Edit profile",
  resetPassword: "Send reset link",
  resendInvite: "Resend invite",
  transferOwnership: "Change ownership",
  transferOwnershipTitle: "Change tenant owner",
  transferOwnershipHint: "Ownership is a single seat. The current owner keeps their account and roles; only the owner seat moves.",
  currentOwner: "Current owner",
  newOwner: "New owner",
  newOwnerPlaceholder: "Select an active tenant user",
  transferOwnershipEmpty: "No other active tenant user is available to receive ownership.",
  transferOwnershipSucceeded: "Tenant ownership was moved.",
  changePassword: "Change password",
  manageRoles: "Manage roles",
  suspend: "Suspend",
  activate: "Activate",
  delete: "Delete",
  restore: "Restore",
  manager: "Manager",
  lastLogin: "Last login",
  never: "Never",
  save: "Save",
  cancel: "Cancel",
  confirm: "Confirm",
  firstName: "First name",
  lastName: "Last name",
  employeeCode: "Employee code",
  jobTitle: "Job title",
  branch: "Branch",
  department: "Department",
  team: "Team (optional)",
  managerId: "Manager UUID (optional)",
  partyId: "Party UUID (optional)",
  password: "New password",
  passwordConfirmation: "Confirm password",
  passwordMismatch: "Passwords must match and contain at least 12 characters.",
  validationSummary: "Review the highlighted fields.",
  requiredField: "This field is required.",
  invalidEmail: "Enter a valid email address.",
  addAssignment: "Add assignment",
  noAssignments: "No role assignments",
  remove: "Remove",
  protectedOwner: "The owner account cannot be edited, re-roled, or deleted. Change ownership first.",
  commandSucceeded: "The action completed successfully.",
  deliveryQueued: "Security email was queued.",
  confirmReset: "Send a password-reset link to this active user? Their password will not change until they use the link.",
  confirmResend: "Rotate the pending invite token and queue a new invitation email?",
  confirmSuspend: "Suspend this user and invalidate their sessions?",
  confirmActivate: "Activate this suspended user?",
  confirmDelete: "Soft-delete this user and invalidate their sessions?",
  confirmRestore: "Restore this deleted user as suspended?",
  loadError: "The tenant access data could not be loaded.",
  loading: "Loading tenant access…",
} as const;

const ar: Record<keyof typeof en, string> = {
  title: "المستخدمون والصلاحيات",
  subtitle: "هويات المستأجر وأدواره ودورة حياته",
  notReady: "يصبح المستخدمون متاحين بعد جاهزية قاعدة بيانات المستأجر.",
  forbidden: "ليست لديك صلاحية عرض مستخدمي المستأجر.",
  retry: "إعادة المحاولة",
  invite: "دعوة مستخدم",
  search: "بحث عن مستخدم",
  apply: "تطبيق الفلاتر",
  clear: "مسح",
  allStatuses: "كل الحالات",
  activeRows: "المستخدمون الحاليون",
  deletedRows: "المستخدمون المحذوفون",
  allRows: "كل المستخدمين",
  allRoles: "كل الأدوار",
  allBranches: "كل الفروع",
  allDepartments: "كل الأقسام",
  allTeams: "كل الفرق",
  name: "الاسم",
  email: "البريد الإلكتروني",
  organization: "الهيكل التنظيمي",
  roles: "الأدوار",
  status: "الحالة",
  actions: "الإجراءات",
  owner: "مالك المستأجر",
  noUsers: "لا يوجد مستخدمون يطابقون الفلاتر.",
  page: "صفحة",
  of: "من",
  previous: "السابق",
  next: "التالي",
  total: "الإجمالي",
  invited: "مدعوون",
  active: "نشطون",
  suspended: "موقوفون",
  deactivated: "معطلون",
  deleted: "محذوفون",
  locked: "مقفلون",
  details: "تفاصيل المستخدم",
  close: "إغلاق",
  edit: "تعديل الملف",
  resetPassword: "إرسال رابط إعادة التعيين",
  resendInvite: "إعادة إرسال الدعوة",
  transferOwnership: "نقل الملكية",
  transferOwnershipTitle: "تغيير مالك المستأجر",
  transferOwnershipHint: "الملكية مقعد واحد. يحتفظ المالك الحالي بحسابه وأدواره؛ ينتقل مقعد الملكية وحده.",
  currentOwner: "المالك الحالي",
  newOwner: "المالك الجديد",
  newOwnerPlaceholder: "اختر مستخدمًا نشطًا للمستأجر",
  transferOwnershipEmpty: "لا يوجد مستخدم نشط آخر يمكن نقل الملكية إليه.",
  transferOwnershipSucceeded: "تم نقل ملكية المستأجر.",
  changePassword: "تغيير كلمة المرور",
  manageRoles: "إدارة الأدوار",
  suspend: "إيقاف",
  activate: "تنشيط",
  delete: "حذف",
  restore: "استعادة",
  manager: "المدير",
  lastLogin: "آخر دخول",
  never: "لم يحدث",
  save: "حفظ",
  cancel: "إلغاء",
  confirm: "تأكيد",
  firstName: "الاسم الأول",
  lastName: "اسم العائلة",
  employeeCode: "الرقم الوظيفي",
  jobTitle: "المسمى الوظيفي",
  branch: "الفرع",
  department: "القسم",
  team: "الفريق (اختياري)",
  managerId: "معرّف المدير (اختياري)",
  partyId: "معرّف الطرف (اختياري)",
  password: "كلمة المرور الجديدة",
  passwordConfirmation: "تأكيد كلمة المرور",
  passwordMismatch: "يجب أن تتطابق كلمتا المرور وألا تقل كل منهما عن 12 حرفاً.",
  validationSummary: "راجع الحقول المحددة.",
  requiredField: "هذا الحقل مطلوب.",
  invalidEmail: "أدخل عنوان بريد إلكتروني صالحًا.",
  addAssignment: "إضافة تعيين",
  noAssignments: "لا توجد تعيينات أدوار",
  remove: "إزالة",
  protectedOwner: "لا يمكن تعديل حساب المالك أو تغيير أدواره أو حذفه. انقل الملكية أولًا.",
  commandSucceeded: "اكتمل الإجراء بنجاح.",
  deliveryQueued: "تمت جدولة رسالة الأمان.",
  confirmReset: "إرسال رابط إعادة تعيين لهذا المستخدم النشط؟ لن تتغير كلمة مروره حتى يستخدم الرابط.",
  confirmResend: "تدوير رمز الدعوة المعلقة وجدولة رسالة دعوة جديدة؟",
  confirmSuspend: "إيقاف المستخدم وإنهاء جلساته؟",
  confirmActivate: "تنشيط هذا المستخدم الموقوف؟",
  confirmDelete: "حذف المستخدم منطقياً وإنهاء جلساته؟",
  confirmRestore: "استعادة المستخدم المحذوف بحالة موقوف؟",
  loadError: "تعذر تحميل بيانات صلاحيات المستأجر.",
  loading: "جارٍ تحميل صلاحيات المستأجر…",
};

export type TenantAccessCopy = typeof en;

export function tenantAccessCopy(locale: TenantAccessLocale): TenantAccessCopy {
  return (locale === "ar" ? ar : en) as TenantAccessCopy;
}
