import type { Language } from "@/i18n/I18nContext";

export const SUBSCRIPTIONS_COPY = {
  en: {
    addon: "Addon", baseTotal: "Applications", addonTotal: "Addons", addonSeats: "Addon seats",
    title: "Subscriptions",
    total: "Total subscriptions",
    activeOnPage: "Active on page",
    scheduledOnPage: "Cancellation scheduled",
    filters: "Filters and ordering",
    status: "Lifecycle status",
    allStatuses: "All statuses",
    tenantId: "Tenant UUIDv7",
    tenantPlaceholder: "019… exact tenant identifier",
    sort: "Order",
    newest: "Newest created",
    oldest: "Oldest created",
    periodSoonest: "Period ending soonest",
    periodLatest: "Period ending latest",
    statusAscending: "Status A–Z",
    statusDescending: "Status Z–A",
    pageSize: "Rows per page",
    apply: "Apply",
    clear: "Reset",
    refresh: "Refresh",
    activeFilters: "active filters",
    loading: "Loading subscriptions…",
    forbidden: "You do not have permission to read subscriptions.",
    permission: "Required permission: admin.subscriptions.read",
    unavailable: "The subscription service is currently unavailable.",
    error: "Subscriptions could not be loaded.",
    retry: "Retry",
    empty: "No subscriptions match the applied filters.",
    invalidTenantId: "Enter an RFC UUIDv7 tenant identifier.",
    tenant: "Tenant",
    lifecycle: "Lifecycle",
    plan: "Canonical plan",
    seats: "Effective seats",
    price: "Recurring total",
    period: "Current period",
    updated: "Updated",
    tenantUnavailable: "Tenant identity unavailable",
    subscriptionId: "Subscription",
    tenantStatus: "Tenant status",
    modules: "modules",
    items: "plan items",
    inspectItems: "Inspect plan items",
    noItems: "No application selections are available.",
    module: "Module",
    tier: "Tier",
    features: "features",
    enrichmentUnavailable: "Catalogue enrichment unavailable",
    notConfigured: "Not configured",
    started: "Started",
    ends: "Ends",
    cancels: "Cancels",
    noCancellation: "No cancellation scheduled",
    baseSeats: "Base users",
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",
    results: "results",
    correlation: "Correlation ID",
    responseAt: "Response at",
    errorCode: "Error code",
  },
  ar: {
    addon: "إضافة", baseTotal: "التطبيقات", addonTotal: "الإضافات", addonSeats: "مقاعد الإضافة",
    title: "الاشتراكات",
    total: "إجمالي الاشتراكات",
    activeOnPage: "النشطة في الصفحة",
    scheduledOnPage: "إلغاء مجدول",
    filters: "التصفية والترتيب",
    status: "حالة دورة الحياة",
    allStatuses: "كل الحالات",
    tenantId: "معرف المستأجر UUIDv7",
    tenantPlaceholder: "019… معرف المستأجر الدقيق",
    sort: "الترتيب",
    newest: "الأحدث إنشاءً",
    oldest: "الأقدم إنشاءً",
    periodSoonest: "الأقرب لانتهاء الفترة",
    periodLatest: "الأبعد لانتهاء الفترة",
    statusAscending: "الحالة تصاعديًا",
    statusDescending: "الحالة تنازليًا",
    pageSize: "عدد الصفوف",
    apply: "تطبيق",
    clear: "إعادة ضبط",
    refresh: "تحديث",
    activeFilters: "عوامل نشطة",
    loading: "جارٍ تحميل الاشتراكات…",
    forbidden: "ليست لديك صلاحية قراءة الاشتراكات.",
    permission: "الصلاحية المطلوبة: admin.subscriptions.read",
    unavailable: "خدمة الاشتراكات غير متاحة حاليًا.",
    error: "تعذر تحميل الاشتراكات.",
    retry: "إعادة المحاولة",
    empty: "لا توجد اشتراكات تطابق عوامل التصفية.",
    invalidTenantId: "أدخل معرف مستأجر RFC UUIDv7 صالحًا.",
    tenant: "المستأجر",
    lifecycle: "دورة الحياة",
    plan: "الخطة الأساسية",
    seats: "المقاعد الفعلية",
    price: "الإجمالي المتكرر",
    period: "الفترة الحالية",
    updated: "آخر تحديث",
    tenantUnavailable: "هوية المستأجر غير متاحة",
    subscriptionId: "الاشتراك",
    tenantStatus: "حالة المستأجر",
    modules: "وحدات",
    items: "بنود خطة",
    inspectItems: "فحص بنود الخطة",
    noItems: "لا تتوفر اختيارات للتطبيقات.",
    module: "الوحدة",
    tier: "الفئة",
    features: "ميزات",
    enrichmentUnavailable: "بيانات الكتالوج الإضافية غير متاحة",
    notConfigured: "غير مضبوط",
    started: "بدأت",
    ends: "تنتهي",
    cancels: "الإلغاء",
    noCancellation: "لا يوجد إلغاء مجدول",
    baseSeats: "المستخدمون الأساسيون",
    previous: "السابق",
    next: "التالي",
    page: "صفحة",
    of: "من",
    results: "نتيجة",
    correlation: "معرف التتبع",
    responseAt: "وقت الاستجابة",
    errorCode: "رمز الخطأ",
  },
} as const;

export type SubscriptionsCopy = (typeof SUBSCRIPTIONS_COPY)[Language];
