import type { CopyShape } from "@/i18n/copy-shape";

export type FleetLanguage = "ar" | "en";

const en = {
  title: "Provisioning fleet",
  subtitle: "Freeze eligible tenant evidence, launch canary-first rollouts, control execution, and attest terminal reports.",
  back: "Provisioning governance",
  directory: "Fleet rollouts",
  previewBuilder: "Create frozen preview",
  previewBuilderHint: "A preview is immutable, expires after 30 minutes, and is a separate caller-owned command from rollout execution.",
  preview: "Preview",
  previewDetail: "Frozen preview",
  rollout: "Rollout",
  rolloutDetail: "Rollout detail",
  tenantEvidence: "Tenant evidence",
  report: "Canonical report",
  attestation: "Report attestation",
  operationType: "Operation type",
  applicationKey: "Application key",
  componentKey: "Component key",
  retentionAcknowledged: "I acknowledge retained tenant data and evidence for decommissioning.",
  targets: "Exact target releases",
  addTarget: "Add target",
  removeTarget: "Remove target",
  targetNumber: "Target",
  componentId: "Component UUIDv7",
  targetReleaseId: "Target release UUIDv7",
  targetReleaseVersion: "Target release version",
  targetManifestChecksum: "Target manifest SHA-256",
  expectedCurrentReleaseId: "Expected current release UUIDv7",
  expectedCurrentManifestChecksum: "Expected current manifest SHA-256",
  currentFenceHint: "UPDATE requires both current-release fence fields. Other operations allow the pair only when both are present.",
  selection: "Tenant selection",
  explicitSelection: "Explicit tenant UUIDs",
  broadSelection: "All eligible tenants",
  broadAcknowledge: "I acknowledge this broad selection may affect every eligible tenant matching the status filter.",
  tenantIds: "Tenant UUIDv7 values",
  tenantId: "Tenant UUIDv7",
  tenantIdsHint: "Separate IDs with commas, spaces, or new lines. Core accepts up to 10,000 IDs, while one synchronous evaluation is currently capped at 500.",
  tenantStatuses: "Tenant statuses",
  active: "Active",
  suspended: "Suspended",
  createPreview: "Create preview",
  confirmPreviewTitle: "Create this immutable preview?",
  confirmPreviewBody: "Core will synchronously evaluate the exact sorted selection and freeze its evidence for 30 minutes.",
  creatingPreview: "Creating preview…",
  createdPreview: "Preview created",
  lookupPreview: "Open preview by UUIDv7",
  previewId: "Preview UUIDv7",
  openPreview: "Open preview",
  refresh: "Refresh",
  loading: "Loading fleet data…",
  emptyRollouts: "No fleet rollouts have been created.",
  emptyTenants: "No tenant evidence exists on this page.",
  forbiddenRollouts: "You do not have permission to read provisioning rollouts.",
  forbiddenPreviewCreate: "Preview creation requires admin.provisioning.rollouts.create.",
  forbiddenRolloutCreate: "Rollout creation requires admin.provisioning.rollouts.create and admin.provisioning.critical.",
  forbiddenManage: "Lifecycle controls require admin.provisioning.rollouts.manage and admin.provisioning.critical.",
  forbiddenReport: "Report access requires admin.provisioning.rollouts.report.",
  forbiddenAttest: "Attestation requires admin.provisioning.rollouts.report and admin.provisioning.critical.",
  unavailable: "Provisioning fleet is temporarily unavailable.",
  notFound: "The requested fleet resource was not found.",
  invalidRouteId: "The route identifier is not a canonical UUIDv7.",
  contractError: "Core returned an unsupported provisioning-fleet response.",
  genericError: "The provisioning-fleet request failed.",
  correlation: "Correlation ID",
  responseAt: "Response time",
  retry: "Retry",
  retryExact: "Retry exact command",
  exactRetryHint: "The outcome is ambiguous. Retry only this unchanged body with the displayed UUIDv7 idempotency key.",
  idempotencyKey: "Idempotency key",
  clearSuccess: "Dismiss",
  commandSucceeded: "Command completed successfully.",
  validationFailed: "Correct the highlighted fields before submitting.",
  stale: "The revision, preview, or evidence is stale. Refresh authoritative state before creating a new intent.",
  conflict: "The command conflicts with the current rollout state.",
  permissionChanged: "Your permission no longer permits this command.",
  errorCode: "Error code",
  currentStatus: "Status",
  createdAt: "Created",
  expiresAt: "Expires",
  operationCommand: "Operation command",
  targetSelectionDigest: "Target-selection digest",
  selectionDigest: "Selection digest",
  eligible: "Eligible",
  ineligible: "Ineligible",
  rank: "Rank",
  safeReason: "Safe reason code",
  eligibilityDigest: "Eligibility digest",
  launchRollout: "Launch rollout",
  launchHint: "Core revalidates the frozen digest and every eligible tenant before accepting this separate critical command.",
  canarySize: "Canary size",
  batchSize: "Batch size",
  maxParallel: "Maximum parallel tenants",
  failureThreshold: "Failure threshold",
  launch: "Launch rollout",
  confirmLaunchTitle: "Launch this critical rollout?",
  confirmLaunchBody: "Core will consume this preview once and begin canary-first scheduling under the exact limits shown.",
  launching: "Launching rollout…",
  rolloutCreated: "Rollout accepted",
  rolloutId: "Rollout UUIDv7",
  total: "Total",
  completed: "Completed",
  failed: "Failed",
  currentBatch: "Current batch",
  revision: "Revision",
  startedAt: "Started",
  pausedAt: "Paused",
  completedAt: "Completed at",
  progress: "Progress",
  open: "Open",
  previous: "Previous",
  next: "Next",
  page: "Page",
  pageSize: "Page size",
  of: "of",
  batch: "Batch",
  operationId: "Tenant operation UUIDv7",
  evidenceDigest: "Completion evidence digest",
  dispatchedAt: "Dispatched",
  lifecycleControls: "Lifecycle controls",
  expectedRevision: "Expected rollout revision",
  reasonCode: "Stable reason code",
  reasonHint: "Use 3–96 uppercase letters, digits, dots, underscores, or hyphens.",
  pause: "Pause rollout",
  resume: "Resume rollout",
  cancel: "Cancel rollout",
  confirmPauseTitle: "Pause this rollout?",
  confirmPauseBody: "Core will stop scheduling additional tenants while preserving already accepted work and append-only evidence.",
  confirmResumeTitle: "Resume this rollout?",
  confirmResumeBody: "Core will resume scheduling only if the revision, state, and failure threshold remain valid.",
  confirmCancelTitle: "Cancel future scheduling?",
  confirmCancelBody: "Cancellation is terminal for future scheduling and does not delete tenant operations or retained evidence.",
  confirmAttestTitle: "Submit this external signature?",
  confirmAttestBody: "Core will verify the Ed25519 signature against the active publisher key and permanently bind it to the canonical report.",
  confirm: "Confirm",
  close: "Close",
  reportNotReady: "The canonical report is not ready until the rollout is terminal.",
  readyForAttestation: "Ready for external signing",
  attested: "Attested",
  payloadBase64: "Canonical signing payload (Base64)",
  signingDigest: "Signing payload SHA-256",
  reportDigest: "Report SHA-256",
  generatedAt: "Generated",
  publisherKeyId: "Active publisher-key UUIDv7",
  signatureAlgorithm: "Signature algorithm",
  signatureBase64: "Ed25519 signature (Base64)",
  signatureHint: "Private signing keys remain outside this browser. Paste only the exact 64-byte Ed25519 signature encoded as 88 Base64 characters.",
  attest: "Attest report",
  attesting: "Attesting report…",
  attestedAt: "Attested",
  attestedByActorRef: "Attesting actor reference",
  copyPayload: "Copy payload",
  copied: "Copied",
  yes: "Yes",
  no: "No",
  none: "—",
  operation: {
    UPDATE: "Update installed components",
    ADD_APPLICATION: "Add Application",
    REPAIR: "Repair component",
    DECOMMISSION: "Decommission component",
  },
  rolloutStatus: {
    DRAFT: "Draft",
    RUNNING: "Running",
    PAUSED: "Paused",
    CANCEL_REQUESTED: "Cancellation requested",
    CANCELLED: "Cancelled",
    SUCCEEDED: "Succeeded",
    FAILED: "Failed",
  },
  tenantStatus: {
    ELIGIBLE: "Eligible",
    INELIGIBLE: "Ineligible",
    PENDING: "Pending",
    DISPATCHED: "Dispatched",
    SUCCEEDED: "Succeeded",
    FAILED: "Failed",
    SKIPPED: "Skipped",
    CANCELLED: "Cancelled",
  },
  validation: {
    operation: "Choose a supported operation.",
    applicationKey: "Use a lowercase Application key of at most 64 characters.",
    componentKey: "Use a valid lowercase dotted component key.",
    required: "This acknowledgement or value is required.",
    notAllowed: "This field is not allowed for the selected operation or selection mode.",
    targetCount: "Provide between 1 and 100 exact targets.",
    repairTargetCount: "Repair requires exactly one target.",
    duplicate: "Values must be unique.",
    uuid: "Enter a canonical UUIDv7.",
    version: "Enter a valid release version of at most 120 characters.",
    sha256: "Enter exactly 64 lowercase hexadecimal characters.",
    pair: "Provide both current-release fence fields or neither.",
    updateRequired: "UPDATE requires both expected-current fence fields.",
    tooMany: "The list exceeds Core's 10,000-ID DTO limit.",
    status: "Tenant statuses must be unique supported values.",
    integer: "Enter a whole number.",
    range: "The value is outside Core's supported range.",
    eligibleBound: "The value cannot exceed the preview's eligible tenant count.",
    parallelBound: "Maximum parallelism cannot exceed canary size, batch size, or eligible count.",
    expired: "This preview has expired; create a new preview.",
    safeCode: "Use 3–96 uppercase letters, digits, dots, underscores, or hyphens.",
    signature: "Enter the exact 88-character Ed25519 Base64 signature.",
  },
} as const;

const ar: CopyShape<typeof en> = {
  title: "أسطول التهيئة",
  subtitle: "جمّد أدلة أهلية المستأجرين، وابدأ عمليات طرح تدريجية، وتحكم في التنفيذ، وصدّق التقارير النهائية.",
  back: "حوكمة التهيئة",
  directory: "عمليات طرح الأسطول",
  previewBuilder: "إنشاء معاينة مجمّدة",
  previewBuilderHint: "المعاينة غير قابلة للتغيير، وتنتهي بعد 30 دقيقة، وهي أمر مستقل عن تنفيذ الطرح وله معرّف خاص به.",
  preview: "المعاينة",
  previewDetail: "المعاينة المجمّدة",
  rollout: "الطرح",
  rolloutDetail: "تفاصيل الطرح",
  tenantEvidence: "أدلة المستأجرين",
  report: "التقرير القياسي",
  attestation: "تصديق التقرير",
  operationType: "نوع العملية",
  applicationKey: "مفتاح التطبيق",
  componentKey: "مفتاح المكوّن",
  retentionAcknowledged: "أقرّ بالاحتفاظ ببيانات المستأجرين وأدلتهم عند إيقاف المكوّن.",
  targets: "الإصدارات المستهدفة الدقيقة",
  addTarget: "إضافة هدف",
  removeTarget: "إزالة الهدف",
  targetNumber: "الهدف",
  componentId: "UUIDv7 للمكوّن",
  targetReleaseId: "UUIDv7 للإصدار المستهدف",
  targetReleaseVersion: "نسخة الإصدار المستهدف",
  targetManifestChecksum: "SHA-256 لبيان الإصدار المستهدف",
  expectedCurrentReleaseId: "UUIDv7 للإصدار الحالي المتوقع",
  expectedCurrentManifestChecksum: "SHA-256 للبيان الحالي المتوقع",
  currentFenceHint: "تتطلب UPDATE حقلي سياج الإصدار الحالي معًا. وتسمح العمليات الأخرى بهما فقط كزوج كامل.",
  selection: "اختيار المستأجرين",
  explicitSelection: "معرّفات مستأجرين محددة",
  broadSelection: "كل المستأجرين المؤهلين",
  broadAcknowledge: "أقرّ بأن هذا الاختيار الواسع قد يؤثر في كل مستأجر مؤهل يطابق مرشح الحالة.",
  tenantIds: "قيم UUIDv7 للمستأجرين",
  tenantId: "UUIDv7 للمستأجر",
  tenantIdsHint: "افصل المعرّفات بفواصل أو مسافات أو أسطر جديدة. يقبل Core حتى 10000 معرّف، بينما التقييم المتزامن الواحد محدود حاليًا بـ500.",
  tenantStatuses: "حالات المستأجر",
  active: "نشط",
  suspended: "معلّق",
  createPreview: "إنشاء المعاينة",
  confirmPreviewTitle: "هل تريد إنشاء هذه المعاينة غير القابلة للتغيير؟",
  confirmPreviewBody: "سيقيّم Core الاختيار الدقيق المرتب ترتيبًا متزامنًا ويجمّد أدلته لمدة 30 دقيقة.",
  creatingPreview: "جارٍ إنشاء المعاينة…",
  createdPreview: "تم إنشاء المعاينة",
  lookupPreview: "فتح معاينة بواسطة UUIDv7",
  previewId: "UUIDv7 للمعاينة",
  openPreview: "فتح المعاينة",
  refresh: "تحديث",
  loading: "جارٍ تحميل بيانات الأسطول…",
  emptyRollouts: "لا توجد عمليات طرح للأسطول.",
  emptyTenants: "لا توجد أدلة مستأجرين في هذه الصفحة.",
  forbiddenRollouts: "ليست لديك صلاحية قراءة عمليات طرح التهيئة.",
  forbiddenPreviewCreate: "يتطلب إنشاء المعاينة صلاحية admin.provisioning.rollouts.create.",
  forbiddenRolloutCreate: "يتطلب إنشاء الطرح صلاحيتي admin.provisioning.rollouts.create وadmin.provisioning.critical.",
  forbiddenManage: "تتطلب عناصر التحكم صلاحيتي admin.provisioning.rollouts.manage وadmin.provisioning.critical.",
  forbiddenReport: "يتطلب الوصول إلى التقرير صلاحية admin.provisioning.rollouts.report.",
  forbiddenAttest: "يتطلب التصديق صلاحيتي admin.provisioning.rollouts.report وadmin.provisioning.critical.",
  unavailable: "أسطول التهيئة غير متاح مؤقتًا.",
  notFound: "لم يتم العثور على مورد الأسطول المطلوب.",
  invalidRouteId: "معرّف المسار ليس UUIDv7 قياسيًا.",
  contractError: "أعاد Core استجابة غير مدعومة لأسطول التهيئة.",
  genericError: "فشل طلب أسطول التهيئة.",
  correlation: "معرّف الارتباط",
  responseAt: "وقت الاستجابة",
  retry: "إعادة المحاولة",
  retryExact: "إعادة الأمر نفسه",
  exactRetryHint: "النتيجة غير محسومة. أعد فقط هذا الطلب دون تغيير وبمفتاح UUIDv7 الظاهر.",
  idempotencyKey: "مفتاح عدم التكرار",
  clearSuccess: "إخفاء",
  commandSucceeded: "اكتمل الأمر بنجاح.",
  validationFailed: "صحّح الحقول المحددة قبل الإرسال.",
  stale: "المراجعة أو المعاينة أو الدليل قديم. حدّث الحالة الموثوقة قبل إنشاء محاولة جديدة.",
  conflict: "يتعارض الأمر مع الحالة الحالية للطرح.",
  permissionChanged: "لم تعد صلاحياتك تسمح بهذا الأمر.",
  errorCode: "رمز الخطأ",
  currentStatus: "الحالة",
  createdAt: "تاريخ الإنشاء",
  expiresAt: "تاريخ الانتهاء",
  operationCommand: "أمر العملية",
  targetSelectionDigest: "بصمة اختيار الأهداف",
  selectionDigest: "بصمة الاختيار",
  eligible: "مؤهل",
  ineligible: "غير مؤهل",
  rank: "الترتيب",
  safeReason: "رمز السبب الآمن",
  eligibilityDigest: "بصمة الأهلية",
  launchRollout: "بدء الطرح",
  launchHint: "يعيد Core التحقق من البصمة المجمّدة ومن كل مستأجر مؤهل قبل قبول هذا الأمر الحرج المستقل.",
  canarySize: "حجم الدفعة التجريبية",
  batchSize: "حجم الدفعة",
  maxParallel: "أقصى عدد متوازٍ",
  failureThreshold: "حد الإخفاق",
  launch: "بدء الطرح",
  confirmLaunchTitle: "هل تريد بدء هذا الطرح الحرج؟",
  confirmLaunchBody: "سيستهلك Core هذه المعاينة مرة واحدة ويبدأ الجدولة التجريبية ضمن الحدود الدقيقة المعروضة.",
  launching: "جارٍ بدء الطرح…",
  rolloutCreated: "تم قبول الطرح",
  rolloutId: "UUIDv7 للطرح",
  total: "الإجمالي",
  completed: "المكتمل",
  failed: "الفاشل",
  currentBatch: "الدفعة الحالية",
  revision: "المراجعة",
  startedAt: "بدأ في",
  pausedAt: "توقف في",
  completedAt: "اكتمل في",
  progress: "التقدم",
  open: "فتح",
  previous: "السابق",
  next: "التالي",
  page: "الصفحة",
  pageSize: "حجم الصفحة",
  of: "من",
  batch: "الدفعة",
  operationId: "UUIDv7 لعملية المستأجر",
  evidenceDigest: "بصمة دليل الإكمال",
  dispatchedAt: "أُرسل في",
  lifecycleControls: "عناصر التحكم في دورة الحياة",
  expectedRevision: "مراجعة الطرح المتوقعة",
  reasonCode: "رمز السبب الثابت",
  reasonHint: "استخدم 3–96 من الأحرف الإنجليزية الكبيرة أو الأرقام أو النقاط أو الشرطات السفلية أو العادية.",
  pause: "إيقاف الطرح مؤقتًا",
  resume: "استئناف الطرح",
  cancel: "إلغاء الطرح",
  confirmPauseTitle: "إيقاف هذا الطرح مؤقتًا؟",
  confirmPauseBody: "سيتوقف Core عن جدولة مستأجرين جدد مع حفظ الأعمال المقبولة والأدلة الإلحاقية.",
  confirmResumeTitle: "استئناف هذا الطرح؟",
  confirmResumeBody: "سيستأنف Core الجدولة فقط إذا ظلت المراجعة والحالة وحد الإخفاق صالحة.",
  confirmCancelTitle: "إلغاء الجدولة المستقبلية؟",
  confirmCancelBody: "الإلغاء نهائي للجدولة المستقبلية ولا يحذف عمليات المستأجرين أو الأدلة المحتفظ بها.",
  confirmAttestTitle: "إرسال هذا التوقيع الخارجي؟",
  confirmAttestBody: "سيتحقق Core من توقيع Ed25519 بواسطة مفتاح الناشر النشط ويربطه نهائيًا بالتقرير القياسي.",
  confirm: "تأكيد",
  close: "إغلاق",
  reportNotReady: "لا يجهز التقرير القياسي حتى يصل الطرح إلى حالة نهائية.",
  readyForAttestation: "جاهز للتوقيع الخارجي",
  attested: "مصدّق",
  payloadBase64: "حمولة التوقيع القياسية (Base64)",
  signingDigest: "SHA-256 لحمولة التوقيع",
  reportDigest: "SHA-256 للتقرير",
  generatedAt: "تاريخ التوليد",
  publisherKeyId: "UUIDv7 لمفتاح ناشر نشط",
  signatureAlgorithm: "خوارزمية التوقيع",
  signatureBase64: "توقيع Ed25519 (Base64)",
  signatureHint: "تبقى مفاتيح التوقيع الخاصة خارج المتصفح. الصق فقط توقيع Ed25519 الدقيق بطول 64 بايت والمشفّر في 88 محرف Base64.",
  attest: "تصديق التقرير",
  attesting: "جارٍ تصديق التقرير…",
  attestedAt: "تاريخ التصديق",
  attestedByActorRef: "مرجع منفذ التصديق",
  copyPayload: "نسخ الحمولة",
  copied: "تم النسخ",
  yes: "نعم",
  no: "لا",
  none: "—",
  operation: {
    UPDATE: "تحديث المكوّنات المثبتة",
    ADD_APPLICATION: "إضافة تطبيق",
    REPAIR: "إصلاح مكوّن",
    DECOMMISSION: "إيقاف مكوّن",
  },
  rolloutStatus: {
    DRAFT: "مسودة",
    RUNNING: "جارٍ التنفيذ",
    PAUSED: "متوقف مؤقتًا",
    CANCEL_REQUESTED: "طُلب الإلغاء",
    CANCELLED: "ملغى",
    SUCCEEDED: "ناجح",
    FAILED: "فاشل",
  },
  tenantStatus: {
    ELIGIBLE: "مؤهل",
    INELIGIBLE: "غير مؤهل",
    PENDING: "قيد الانتظار",
    DISPATCHED: "مُرسل",
    SUCCEEDED: "ناجح",
    FAILED: "فاشل",
    SKIPPED: "متخطى",
    CANCELLED: "ملغى",
  },
  validation: {
    operation: "اختر عملية مدعومة.",
    applicationKey: "استخدم مفتاح تطبيق بأحرف صغيرة وبحد أقصى 64 محرفًا.",
    componentKey: "استخدم مفتاح مكوّن منقطًا صالحًا بأحرف صغيرة.",
    required: "هذه القيمة أو الموافقة مطلوبة.",
    notAllowed: "هذا الحقل غير مسموح للعملية أو نمط الاختيار المحدد.",
    targetCount: "أدخل من هدف واحد إلى 100 هدف دقيق.",
    repairTargetCount: "يتطلب الإصلاح هدفًا واحدًا فقط.",
    duplicate: "يجب ألا تتكرر القيم.",
    uuid: "أدخل UUIDv7 قياسيًا.",
    version: "أدخل نسخة إصدار صالحة بحد أقصى 120 محرفًا.",
    sha256: "أدخل 64 محرفًا سداسيًا عشريًا صغيرًا بالضبط.",
    pair: "أدخل حقلي سياج الإصدار الحالي معًا أو اتركهما معًا.",
    updateRequired: "تتطلب UPDATE حقلي سياج الحالة الحالية.",
    tooMany: "تتجاوز القائمة حد DTO البالغ 10000 معرّف.",
    status: "يجب أن تكون حالات المستأجر فريدة ومدعومة.",
    integer: "أدخل عددًا صحيحًا.",
    range: "القيمة خارج النطاق المدعوم في Core.",
    eligibleBound: "لا يمكن أن تتجاوز القيمة عدد المستأجرين المؤهلين في المعاينة.",
    parallelBound: "لا يمكن أن يتجاوز التوازي حجم الدفعة التجريبية أو الدفعة أو عدد المؤهلين.",
    expired: "انتهت هذه المعاينة؛ أنشئ معاينة جديدة.",
    safeCode: "استخدم 3–96 من الأحرف الكبيرة أو الأرقام أو النقاط أو الشرطات.",
    signature: "أدخل توقيع Ed25519 بصيغة Base64 وبطول 88 محرفًا بالضبط.",
  },
};

export type ProvisioningFleetCopy = CopyShape<typeof en>;

export function getProvisioningFleetCopy(language: FleetLanguage): ProvisioningFleetCopy {
  return language === "ar" ? ar : en;
}
