import type { Language } from "@/i18n/I18nContext";

export const LOGGING_COPY = {
  en: {
    title: "Runtime logging",
    readPermission: "Required permission: admin.logging.read",
    updatePermission:
      "Required permissions: admin.logging.update + admin.logging.critical",
    livePermission:
      "Required permissions: admin.logging.read + admin.logging.critical",
    directory: "Override directory",
    directoryHelp:
      "Active rows are ordered by most recently updated. Pagination is cursorless because Core returns a bounded array without totals.",
    activeOnPage: "Active on page",
    rowsOnPage: "Rows on page",
    filters: "Filters",
    scope: "Scope",
    allScopes: "All scopes",
    app: "Service",
    allApps: "All services",
    tenantId: "Tenant UUIDv7",
    includeExpired: "Include expired overrides",
    pageSize: "Rows per page",
    apply: "Apply",
    reset: "Reset",
    refresh: "Refresh",
    page: "Page",
    previous: "Previous",
    next: "Next",
    target: "Target",
    level: "Level",
    reason: "Reason",
    expires: "Expires",
    updated: "Updated",
    actions: "Actions",
    global: "All services and tenants",
    noTenant: "No tenant",
    active: "Active",
    expired: "Expired",
    edit: "Edit",
    remove: "Remove",
    editor: "Temporary override",
    editorHelp:
      "The target shape is exact: GLOBAL has no target, APP has a service, TENANT has a tenant, and TENANT_APP has both.",
    expiresAt: "Expiry (local time)",
    expiryHelp: "Required, future, and no more than 24 hours from now.",
    save: "Review and save",
    readOnlyEditor: "You can inspect overrides but cannot change them.",
    effective: "Effective-level inspector",
    effectiveHelp:
      "Resolve the current precedence: TENANT_APP > TENANT > APP > GLOBAL > warn fallback.",
    resolve: "Resolve effective level",
    source: "Policy source",
    history: "Append-only history",
    overrideId: "Override UUIDv7",
    action: "Action",
    allActions: "All actions",
    actor: "Actor",
    previousValue: "Previous",
    newValue: "New",
    live: "Live sanitized logs",
    liveHelp:
      "Start explicitly. The stream reconnects with bounded backoff and becomes stale if Core heartbeats stop.",
    minimumLevel: "Minimum level",
    start: "Start stream",
    stop: "Stop and clear",
    clear: "Clear buffer",
    retryNow: "Reconnect now",
    liveIdle: "The live stream is stopped.",
    liveConnecting: "Connecting to the authorized stream…",
    liveReady: "Live",
    liveReconnecting: "Reconnecting",
    liveStale: "No heartbeat was received; reconnecting.",
    livePaused:
      "Privacy pause: the tab was hidden, so the connection and in-memory buffer were cleared.",
    privacy:
      "Privacy boundary: at most 200 events stay in memory. Context and user identifiers are discarded, nothing is persisted, and hiding the tab or stopping clears the buffer.",
    receivedAt: "Last stream activity",
    service: "Service",
    timestamp: "Timestamp",
    message: "Message",
    correlation: "Correlation ID",
    reconnectAttempt: "Reconnect attempt",
    loading: "Loading runtime logging data…",
    emptyDirectory: "No overrides match these filters.",
    emptyHistory: "No history rows match these filters.",
    forbidden: "You do not have permission to access this capability.",
    unavailable: "The logging service is currently unavailable.",
    stale:
      "Showing last-known data because the authoritative refresh failed.",
    error: "Runtime logging data could not be loaded.",
    retry: "Retry",
    invalidUuid: "Enter an RFC UUIDv7 identifier.",
    appRequired: "Select a service for this scope.",
    tenantRequired: "Enter a tenant UUIDv7 for this scope.",
    reasonInvalid: "Enter a reason of 1–255 characters.",
    expiryInvalid:
      "Choose a future expiry no more than 24 hours from now.",
    confirmUpsert: "Confirm temporary override",
    confirmDelete: "Confirm override removal",
    confirmUpsertDetail:
      "This changes runtime verbosity immediately across connected replicas until the expiry.",
    confirmDeleteDetail:
      "This soft-deletes the override and republishes the effective policy snapshot.",
    cancel: "Cancel",
    confirm: "Confirm critical action",
    saving: "Saving override…",
    deleting: "Removing override…",
    success: "The logging policy mutation was accepted.",
    validationFailure: "The command failed validation.",
    conflict: "The override changed or conflicts with another command.",
    mutationForbidden: "You cannot perform this critical logging change.",
    mutationUnavailable: "The logging command endpoint is unavailable.",
    unknownOutcome:
      "The write outcome is unknown. Retry the exact intent with its retained UUIDv7 key, or perform authoritative readback.",
    mutationError: "The logging policy mutation failed.",
    retryExact: "Retry exact intent",
    reconcile: "Authoritative readback",
    dismiss: "Dismiss",
    errorCode: "Error code",
    responseAt: "Response at",
    notRecorded: "Not recorded",
    fallback: "Default warn fallback",
    legacyPermanent: "No expiry recorded (legacy row)",
  },
  ar: {
    title: "سجلات التشغيل",
    readPermission: "الصلاحية المطلوبة: admin.logging.read",
    updatePermission:
      "الصلاحيات المطلوبة: admin.logging.update + admin.logging.critical",
    livePermission:
      "الصلاحيات المطلوبة: admin.logging.read + admin.logging.critical",
    directory: "دليل التجاوزات",
    directoryHelp:
      "تُرتب الصفوف النشطة حسب آخر تحديث. التقسيم دون إجمالي لأن Core يعيد مصفوفة محدودة فقط.",
    activeOnPage: "النشطة في الصفحة",
    rowsOnPage: "صفوف الصفحة",
    filters: "عوامل التصفية",
    scope: "النطاق",
    allScopes: "كل النطاقات",
    app: "الخدمة",
    allApps: "كل الخدمات",
    tenantId: "معرف المستأجر UUIDv7",
    includeExpired: "تضمين التجاوزات المنتهية",
    pageSize: "عدد الصفوف",
    apply: "تطبيق",
    reset: "إعادة ضبط",
    refresh: "تحديث",
    page: "صفحة",
    previous: "السابق",
    next: "التالي",
    target: "الهدف",
    level: "المستوى",
    reason: "السبب",
    expires: "الانتهاء",
    updated: "آخر تحديث",
    actions: "الإجراءات",
    global: "كل الخدمات والمستأجرين",
    noTenant: "دون مستأجر",
    active: "نشط",
    expired: "منتهي",
    edit: "تعديل",
    remove: "إزالة",
    editor: "تجاوز مؤقت",
    editorHelp:
      "شكل الهدف دقيق: GLOBAL بلا هدف، وAPP بخدمة، وTENANT بمستأجر، وTENANT_APP بكليهما.",
    expiresAt: "الانتهاء (بالتوقيت المحلي)",
    expiryHelp: "إلزامي وفي المستقبل وبحد أقصى 24 ساعة من الآن.",
    save: "مراجعة وحفظ",
    readOnlyEditor: "يمكنك فحص التجاوزات لكن لا يمكنك تغييرها.",
    effective: "فاحص المستوى الفعلي",
    effectiveHelp:
      "احسب الأولوية الحالية: TENANT_APP ثم TENANT ثم APP ثم GLOBAL ثم warn الافتراضي.",
    resolve: "حساب المستوى الفعلي",
    source: "مصدر السياسة",
    history: "السجل الإلحاقي",
    overrideId: "معرف التجاوز UUIDv7",
    action: "الإجراء",
    allActions: "كل الإجراءات",
    actor: "المنفذ",
    previousValue: "السابق",
    newValue: "الجديد",
    live: "السجلات المباشرة المنقحة",
    liveHelp:
      "ابدأ يدويًا. يعيد البث الاتصال بتأخير محدود ويصبح قديمًا إذا توقفت نبضات Core.",
    minimumLevel: "أدنى مستوى",
    start: "بدء البث",
    stop: "إيقاف ومسح",
    clear: "مسح الذاكرة",
    retryNow: "إعادة الاتصال الآن",
    liveIdle: "البث المباشر متوقف.",
    liveConnecting: "جارٍ الاتصال بالبث المصرح…",
    liveReady: "مباشر",
    liveReconnecting: "إعادة اتصال",
    liveStale: "لم تصل نبضة؛ جارٍ إعادة الاتصال.",
    livePaused:
      "إيقاف للخصوصية: أُخفيت علامة التبويب، لذا أُغلق الاتصال ومُسحت الذاكرة.",
    privacy:
      "حد الخصوصية: يبقى 200 حدث كحد أقصى في الذاكرة. تُحذف تفاصيل السياق ومعرفات المستخدمين، ولا يُحفظ شيء، ويؤدي إخفاء التبويب أو الإيقاف إلى المسح.",
    receivedAt: "آخر نشاط للبث",
    service: "الخدمة",
    timestamp: "الوقت",
    message: "الرسالة",
    correlation: "معرف التتبع",
    reconnectAttempt: "محاولة إعادة الاتصال",
    loading: "جارٍ تحميل بيانات سجلات التشغيل…",
    emptyDirectory: "لا توجد تجاوزات تطابق عوامل التصفية.",
    emptyHistory: "لا توجد سجلات تاريخ تطابق عوامل التصفية.",
    forbidden: "ليست لديك صلاحية الوصول إلى هذه الإمكانية.",
    unavailable: "خدمة السجلات غير متاحة حاليًا.",
    stale: "تُعرض آخر بيانات معروفة لأن التحديث الموثوق فشل.",
    error: "تعذر تحميل بيانات سجلات التشغيل.",
    retry: "إعادة المحاولة",
    invalidUuid: "أدخل معرف RFC UUIDv7 صالحًا.",
    appRequired: "اختر خدمة لهذا النطاق.",
    tenantRequired: "أدخل معرف مستأجر UUIDv7 لهذا النطاق.",
    reasonInvalid: "أدخل سببًا من 1 إلى 255 حرفًا.",
    expiryInvalid: "اختر انتهاءً مستقبليًا لا يتجاوز 24 ساعة.",
    confirmUpsert: "تأكيد التجاوز المؤقت",
    confirmDelete: "تأكيد إزالة التجاوز",
    confirmUpsertDetail:
      "يغيّر هذا مستوى سجلات التشغيل فورًا عبر النسخ المتصلة حتى وقت الانتهاء.",
    confirmDeleteDetail:
      "يحذف هذا التجاوز منطقيًا ويعيد نشر لقطة السياسة الفعلية.",
    cancel: "إلغاء",
    confirm: "تأكيد الإجراء الحرج",
    saving: "جارٍ حفظ التجاوز…",
    deleting: "جارٍ إزالة التجاوز…",
    success: "قُبل تعديل سياسة السجلات.",
    validationFailure: "فشل التحقق من الأمر.",
    conflict: "تغير التجاوز أو يتعارض مع أمر آخر.",
    mutationForbidden: "لا يمكنك تنفيذ هذا التغيير الحرج.",
    mutationUnavailable: "نقطة أمر السجلات غير متاحة.",
    unknownOutcome:
      "نتيجة الكتابة غير معروفة. أعد محاولة النية نفسها بمفتاح UUIDv7 المحتفظ به، أو نفّذ قراءة موثوقة.",
    mutationError: "فشل تعديل سياسة السجلات.",
    retryExact: "إعادة النية نفسها",
    reconcile: "قراءة موثوقة",
    dismiss: "إغلاق",
    errorCode: "رمز الخطأ",
    responseAt: "وقت الاستجابة",
    notRecorded: "غير مسجل",
    fallback: "القيمة الافتراضية warn",
    legacyPermanent: "لا يوجد انتهاء مسجل (صف قديم)",
  },
} as const;

export type LoggingCopy = (typeof LOGGING_COPY)[Language];
